### ISSUE TITLE
Problem mit Öffnungszeiten-Fehlern

### ISSUE THREAD

**Issue by lud-bmgrt** [bleibtoffen/bleibtoffen#100]
Hallo Claas, hallo Christian,
wenn ich bei der opening-hour-Eingabe über JOSM kleine Fehlerchen mache und dann hochlade -scheint alles o.k.....Prüfen kann man erst, wenn nach ca. einer Stunde bleibtoffen etwas anzeigt anzeigt, was dann falsch war.
Wenn -wie ich hoffe- aus eurem "bleibtoffen" ein allgemeines "ist-offen" Öffnungzeitentool wird, sollten unsere Editoren wie zB JOSM strenger die opening-hour-Eingaben prüfen - oder?
(Ein Fehler war, dass ich ein blank vergessen hatte, ein anderer: einen Wochentag ein zweites Mal mit einer weiteren Zeit genannt)
mhG Ludwig
sh@bwgis.eu
p.s. manche Rathäuser machen mit (Rielasingen-Worblingen südlich von Singen BW, angrenzend an den Kanton Schaffhausen)

**Comment by chnuessli** [comment]
Hallo Ludwig

Kennst du das Plugin OpeningHoursEditor?
Dies prüft deine Eingaben und macht Tests auf ihre Plausabilität.
https://wiki.openstreetmap.org/wiki/JOSM/Plugins/OpeningHoursEditor
JOSM/Plugins/OpeningHoursEditor - OpenStreetMap Wiki<https://wiki.openstreetmap.org/wiki/JOSM/Plugins/OpeningHoursEditor>
OpeningHoursEditor is a plugin for JOSM.It provides a graphical editor for editing opening_hours.It can also be used to edit other time related tags like collection_times for postboxes or lit for highways. At the moment the plugin is still in development.
wiki.openstreetmap.org

**Comment by datendelphin** [comment]
Also der openinghourseditor ist schon recht praktisch, weil er das visuell darstellt. Aber er ist weit weg von vollständig. z.B. unterstützt er nicht ein mal PH (public holidays) off, was bei fast allen Öffnungszeiten zur Anwendung kommt.

**Comment by lud-bmgrt** [comment]
Danke, Christian und Michael. Diesen versuchte ich schon zu aktivieren, jetzt auch nochmal: aber ich finde ihn nicht in meinem JOSM V16239 unter kubuntu, alle anderen plugins finde ich .... könnt ihr mir einen Hinweis geben?

**Comment by datendelphin** [comment]
also bei mir funktioniert download, dann suchen nach opening
