### ISSUE TITLE
Blog-Artikel übersetzen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#2]
**Ziel**: Blog-Artikel aus dem Französischen übersetzen: https://blog.caresteouvert.fr/

**Tipp**: Mit [DeepL](https://www.deepl.com/translator) vorübersetzen und anschließend fein-tunen.

**Zu übersetzende Artikel**:

- [x] [Que faire s’il manque un commerce dans Ça reste ouvert ?](https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert/)
  (Was tun, wenn ein Geschäft fehlt in "Ça reste ouvert"?)
- [x] [Appel public à contribuer sur le site “Ça reste ouvert”](https://blog.caresteouvert.fr/appel-public-a-contribuer-sur-le-site-ca-reste-ouvert/)
  (Öffentlicher Aufruf zur Mitarbeit an der Seite ""Ça reste ouvert"")
- [x] [“Ça Reste Ouvert ” : un outil de communication des mairies](https://blog.caresteouvert.fr/un-outil-de-communication-des-mairies/)
  ("Ça reste ouvert" - ein Kommunikationswerkzeug für Rathäuser)

Quelltexte: siehe https://github.com/osmontrouge/caresteouvert/issues/154

**Comment by ChristineKarch** [comment]
Das kann ich uebernehmen. Ich würde jeweils eine Draft-Version auf einem Pad (pads.ccc.de) machen und dann hier verlinken.

**Comment by caugner** [comment]
Perfekt, danke dir!

**Comment by ChristineKarch** [comment]
**Was tun, wenn ein Geschäft fehlt in "Ça reste ouvert"?**

https://pads.ccc.de/MpKFr48pOb


![Screenshot1-Bearbeiten](https://user-images.githubusercontent.com/15981021/78405943-de02ed00-7601-11ea-82be-1c388f97d08c.png)

![Screenshot2 Punkt](https://user-images.githubusercontent.com/15981021/78405969-e9eeaf00-7601-11ea-8512-df0f74c1db90.png)

![Screenshot3 Apotheke](https://user-images.githubusercontent.com/15981021/78405982-efe49000-7601-11ea-92f4-f24fb88110d7.png)

![Screenshot4 Objekt bearbeiten](https://user-images.githubusercontent.com/15981021/78405994-f70b9e00-7601-11ea-9129-12578f33a616.png)

![Screenshot5 Hochladen](https://user-images.githubusercontent.com/15981021/78406010-fecb4280-7601-11ea-8733-43ab9f1145c0.png)

**Comment by giggls** [comment]
> Das kann ich uebernehmen. Ich würde jeweils eine Draft-Version auf einem Pad (pads.ccc.de) machen und dann hier verlinken.

Wichtiger scheint mir grade fast zu sein die Wiki-Seite auf Deutch zu übersetzen.
Von englisch krieg ich das auch hin von französisch nicht.

**Comment by ChristineKarch** [comment]
**Öffentlicher Aufruf zur Mitarbeit an der Seite "Ça reste ouvert"**

https://pads.ccc.de/UYfb1oQuWy

![Screenshot6 CaRestOuvert Carte](https://user-images.githubusercontent.com/15981021/78410662-499e8780-760d-11ea-9b9d-d9cdfad0c4b7.png)

**Comment by ChristineKarch** [comment]
> Wichtiger scheint mir grade fast zu sein die Wiki-Seite auf Deutch zu übersetzen.
> Von englisch krieg ich das auch hin von französisch nicht.

Ich mach hier noch fertig (habs fast), dann schau ich mirs wiki an :)

**Comment by ChristineKarch** [comment]
**"Ça reste ouvert" - ein Kommunikationswerkzeug für Rathäuser**

https://pads.ccc.de/lolASNCkqr

![Screenshot7 Attribute](https://user-images.githubusercontent.com/15981021/78424556-b7c76680-766e-11ea-82a8-2cb3860524a2.png)

**Comment by ChristineKarch** [comment]
Alle drei pads sind jetzt soweit fertig. Alles was abgeändert werden muss (unsere Domain, einzufügende Links, etc.) hab ich in BLOCK markiert.

Sprachlich bin ich beim dritten pad über die "Akteure" gestolpert, wie sagt man denn da auf Deutsch? Wenn jemand eine Idee hat, pass ich es an (oder selber anpassen).

**Comment by caugner** [comment]
@ChristineKarch Ich finde "Akteure" da nicht so schlimm, bin mir aber auch nicht sicher, was dort im Französischen jetzt genau gemeint ist. Öffentliche Träger sind nicht gemeint, oder?

@jens1o @datendelphin Hättet ihr Zeit, die Blog-Artikel korrekturzulesen?

**Comment by jens1o** [comment]
Erledigt; ich hab die Tippfehlerkorrektur direkt in den Pads durchgezogen. :)

Mir wäre es aber lieber, dass man die Nutzer duzt. In der Anleitung ist momentan noch als einziges _nicht_ die Höflichkeitsform in Verwendung. Ist das absichtlich so gewählt worden?

**Comment by ChristineKarch** [comment]
Am Anfang bin ich auch davon ausgegangen, dass wir die Leute duzen, das hat auch in der Anleitung gut gepasst. Aber die anderen beiden Texte richten sich ja eigentlich an Behörden, da bin ich das duzen nicht gewöhnt ..Trotzdem sollte man es wohl irgendwie konsistent machen :)

**Comment by caugner** [comment]
In der deutschen Oberfläche habe ich auch geduzt, aber im Artikel für Behörden kann man ruhig siezen. Die Inkonsistenz finde ich nicht so schlimm.

**Comment by caugner** [comment]
Danke, ich habe die Blog-Einträge nun als HTML in das Repository übernommen.
