### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ChristineKarch** [bleibtoffen/bleibtoffen#21]
Ich bin gerade ueber diesen Satz gestolpert in einem der Blogartikel:

> La société Jungle Bus autorise à titre gracieux tout usage de la marque et du logo “ça reste ouvert” par les collectivités territoriales dans le cadre de leur mission de service public.

bzw. auf deutsch

> Das Unternehmen Jungle bus genehmigt kostenlos jede Nutzung der Marke und des Logos "ça reste ouvert" durch lokale Behörden im Rahmen ihres öffentlichen Auftrags.

Wir brauchen ja irgendwie ein Logo. Macht uns Jungle Bus ein deutsches?

**Comment by caugner** [comment]
> Macht uns Jungle Bus ein deutsches?

Ich vermute, dass mit dem internationalen Namen auch ein internationales Logo kommt.

**Comment by caugner** [comment]
Schließe das Issue erstmal analog zu #5.

**Comment by caugner** [comment]
Wir nehmen jetzt doch **Bleibt offen** für den deutschsprachigen Bereich.

Daher ein erster Entwurf für das (mobile) Logo (Schriftart nicht final):

![grafik](https://user-images.githubusercontent.com/495429/78693204-36d0cf00-78fb-11ea-8ffb-e94483d55ef2.png)

Folgende Probleme:
* "bleibtoffen" ohne Domainendung ist zu kurz
* "Ausgangssperre" ist nicht das gleiche wie "Ausgangsbeschränkung" und "Kontaktverbot" (DE)

**Comment by ChristineKarch** [comment]
Die Geschaefte sind ja nicht aufgrund Ausgangssperre, etc. geschlossen, von dem her wuerde ich das nicht in diese Richtung bezeichnen. Mach doch als zweite Zeile "#FlattenTheCurve". Wir muessen ja nicht uebersetzen.

**Comment by caugner** [comment]
Gute Idee, wobei ich FlattenTheCurve noch etwas zu kurz fände:

![grafik](https://user-images.githubusercontent.com/495429/78695258-2a01aa80-78fe-11ea-9ff5-9c47049cb637.png)

Das Logo wird übrigens hier in der mobilen Ansicht ohne zusätzlichen Text angezeigt:

![grafik](https://user-images.githubusercontent.com/495429/78695040-d8592000-78fd-11ea-80c6-9660d4666789.png)

**Comment by ChristineKarch** [comment]
probier mal ohne de, dann passt es wieder zusammen, ich glaube das waere ganz gut :)

**Comment by chnuessli** [comment]
#stayhome wäre auch noch eine Alternative?

Freundliche Grüsse

Christian Nüssli
________________________________
Von: Christine Karch <notifications@github.com>
Gesendet: Tuesday, April 7, 2020 6:34:57 PM
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


probier mal ohne de, dann passt es wieder zusammen, ich glaube das waere ganz gut :)

**Comment by caugner** [comment]
Oder wir verzichten ganz auf die zweite Zeile im mobilen Logo.

**Comment by chnuessli** [comment]
Wäre auch gut. Dann muss man sich nicht zu etwas commiten?
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Dienstag, 7. April 2020 18:45
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


Oder wir verzichten ganz auf die zweite Zeile im mobilen Logo.

**Comment by caugner** [comment]
Blau/grün:
![grafik](https://user-images.githubusercontent.com/495429/78697135-a3020180-7900-11ea-81e4-2e14fccd348c.png)

Gelb/grün:
![grafik](https://user-images.githubusercontent.com/495429/78697309-e9576080-7900-11ea-9bab-1c341295209d.png)

**Comment by caugner** [comment]
**Text unter dem Logo in der Sidebar**:

1. Die Karte mit den Orten, die offen bleiben.
  ![grafik](https://user-images.githubusercontent.com/495429/78697747-9205c000-7901-11ea-8239-2847bb106da2.png)
2. Die Orte, die weiterhin geöffnet sind.
  ![grafik](https://user-images.githubusercontent.com/495429/78697984-e9a42b80-7901-11ea-9ee1-7d5b972db1c6.png)

**Comment by chnuessli** [comment]
Logo Grün/Blau und 2. Slogan: Die Orte, die weiterhin geöffnet sind.

Was meint ihr?
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Dienstag, 7. April 2020 19:00
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


Text unter dem Logo in der Sidebar:

  1.  Die Karte mit den Orten, die offen bleiben.
[grafik]<https://user-images.githubusercontent.com/495429/78697747-9205c000-7901-11ea-8239-2847bb106da2.png>
  2.  Die Orte, die weiterhin geöffnet sind.
[grafik]<https://user-images.githubusercontent.com/495429/78697984-e9a42b80-7901-11ea-9ee1-7d5b972db1c6.png>

**Comment by caugner** [comment]
Ich fand das gelb/grüne besser, weil es näher am Original ist und ich das Blau als zu intensiv empfand (neben dem grün).

**Comment by chnuessli** [comment]
Auch gut sieht auf Mobile vermutlich auch besser aus
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Dienstag, 7. April 2020 19:19
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


Ich fand das gelb/grüne besser, weil es näher am Original ist und ich das Blau als zu intensiv empfand (neben dem grün).

**Comment by caugner** [comment]
@ChristineKarch Einwände?

**Comment by ChristineKarch** [comment]
Gelb/Grün find ich auch gut :)

**Comment by caugner** [comment]
Gerade kam der berechtigte Einwand von Florian (frz. Projektleiter) zum mobilen Logo ohne Slogan: Die User sehen nur das, keine weitere Information.

Also vielleicht doch:

1. Karte offener Orte
 ![grafik](https://user-images.githubusercontent.com/495429/78701342-26beec80-7907-11ea-83a1-a423b160c30b.png)
2. Bäcker, Apotheke & Co
 ![grafik](https://user-images.githubusercontent.com/495429/78701688-bc5a7c00-7907-11ea-94ad-4397be347a29.png)
3. trotz COVID-19-Maßnahmen:
  ![grafik](https://user-images.githubusercontent.com/495429/78702039-40acff00-7908-11ea-93cb-2b04ab4efa02.png)
4. trotz Coronavirus:
  ![grafik](https://user-images.githubusercontent.com/495429/78702096-5ae6dd00-7908-11ea-9b25-e2fef6477ace.png)

**Comment by ChristineKarch** [comment]
ich bin fuer 2) und bitte wieder blau-gelb und unten dann gruen

3) und 4) gefaellt mir weniger

bei 1) stoer ich mich an den "Orten", sollte eher Geschaefte heissen, aber dann ist es wohl zu lang

**Comment by caugner** [comment]
> ich bin fuer 2) und bitte wieder blau-gelb und unten dann gruen

![grafik](https://user-images.githubusercontent.com/495429/78703082-e7de6600-7909-11ea-8b3e-4ee63f48bced.png)

Alternativ gelb/grün/blau, damit "offen" grün bleibt (analog zu offenen Geschäften in der Karte):

![grafik](https://user-images.githubusercontent.com/495429/78702766-64bd1000-7909-11ea-823e-d4431ad28bb1.png)

**Comment by chnuessli** [comment]
Bin auch für 2) das Offen = Grün symbolisiert schön dass die Geschäffte geöffnet sind.

________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Dienstag, 7. April 2020 19:58
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


ich bin fuer 2) und bitte wieder blau-gelb und unten dann gruen

[grafik]<https://user-images.githubusercontent.com/495429/78703082-e7de6600-7909-11ea-8b3e-4ee63f48bced.png>

Alternativ gelb/grün/blau, damit "offen" grün bleibt (analog zu offenen Geschäften in der Karte):

[grafik]<https://user-images.githubusercontent.com/495429/78702766-64bd1000-7909-11ea-823e-d4431ad28bb1.png>

**Comment by caugner** [comment]
Habe inzwischen die richtige Schriftart (Spirited Sans):

![grafik](https://user-images.githubusercontent.com/495429/78704006-7dc6c080-790b-11ea-82bf-eaf049f60798.png)

**Comment by caugner** [comment]
`Apotheke, Bäcker & Co` wäre alphabetisch sortiert (ABC):

![grafik](https://user-images.githubusercontent.com/495429/78704459-28d77a00-790c-11ea-9479-beb893f9e6bd.png)


`Was weiterhin geöffnet hat` wäre etwas irritierend, aber vielleicht trotzdem gut:

![grafik](https://user-images.githubusercontent.com/495429/78704408-18bf9a80-790c-11ea-8934-94eca736dc58.png)

**Comment by ChristineKarch** [comment]
Beides gut, aber nicht rot .. lieber blau

**Comment by caugner** [comment]
> Beides gut, aber nicht rot .. lieber blau

![grafik](https://user-images.githubusercontent.com/495429/78705988-9e444a00-790e-11ea-9ad6-128a05ad5a8c.png)

**Comment by datendelphin** [comment]
Fleissig! Gefällt mir auch. Kann nicht sagen, welches besser ist

**Comment by caugner** [comment]
Zu "Apotheke, Bäcker & Co": Eigentlich fehlt hier der "Supermarkt", was wohl für die meisten Leute am wichtigsten sein dürfte. Daher tendiere ich mehr zu "Was weiterhin geöffnet hat".

Kann allerdings inzwischen auch nicht mehr so klar denken.

**Comment by ChristineKarch** [comment]
Ich glaube, wenn Leute Apotheke, Bäcker, ... lesen, denken sie sofort automatisch Supermarkt. Das ist total naheliegend. "Was weiterhin gehöffnet hat" ist zwar formal richtiger, aber auch irgendwie trockener. Ich bin für den Apotheker :)

**Comment by caugner** [comment]
Ich warte noch auf Feedback von @chnuessli @giggls und @jens1o.
Idealerweise treffen wir eine Entscheidung bis morgen Mittwoch um 13 Uhr, damit das französische Team uns bis morgen Abend die fertigen Logos liefern kann.

Hier schon einmal das voraussichtliche Logo für die Desktop-Sidebar (in der finalen Version dann mit weniger Abstand):
![grafik](https://user-images.githubusercontent.com/495429/78709097-668bd100-7913-11ea-8387-8f4da0be347e.png)

**Comment by chnuessli** [comment]
Ich schliesse mich Christine an, das erste klingt etwas frischer mit dem Apotheker usw. Ist aber recht eingeschränkt, das Zweite ist eindeutiger wirkt aber altbacken.

Also gehen wir mit dem Apotheker... Apotheker, Einkauf & Co? Bäcker sind doch vermutlich die kleinsten Datenanteile?


________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Dienstag, 7. April 2020 21:05
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


Ich warte noch auf Feedback von @chnuessli<https://github.com/chnuessli> @giggls<https://github.com/giggls> und @jens1o<https://github.com/jens1o>.
Idealerweise treffen wir eine Entscheidung bis morgen Mittwoch um 13 Uhr, damit das französische Team uns bis morgen Abend die fertigen Logos liefern kann.

Hier schon einmal das voraussichtliche Logo für die Desktop-Sidebar (in der finalen Version dann mit weniger Abstand):
[grafik]<https://user-images.githubusercontent.com/495429/78709097-668bd100-7913-11ea-8387-8f4da0be347e.png>

**Comment by datendelphin** [comment]
Also bei uns gibt es schon ziemlich viele Bäckereien. Und mir gefällt das A... B... C. :smile:

**Comment by chnuessli** [comment]
Gut dann, Apotheke, Bäcker & Co 👍🏼

Freundliche Grüsse

Christian Nüssli
________________________________
Von: datendelphin <notifications@github.com>
Gesendet: Tuesday, April 7, 2020 10:12:09 PM
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


Also bei uns gibt es schon ziemlich viele Bäckereien. Und mir gefällt das A... B... C. 😄

**Comment by caugner** [comment]
Allerletzte Frage:

1. `Apotheke, Bäcker & Co`
2. `Apotheke, Bäcker & Co.`

In Deutschland gibt es diese Zoosendungen, die haben häufiger einen Punkt hinter `Co` als nicht: https://www.hoerzu.de/zoo-im-tv-programm/

PS: Offizielle Schreibweise ist wohl immer `Co.`, dann würde ich es analog halten: https://de.m.wikipedia.org/wiki/Elefant,_Tiger_%26_Co.

**Comment by ChristineKarch** [comment]
Ich finde es sieht gut aus ohne Punkt, wenn man oben auf deine Grafik schaut. Mir fehlt nichts, aber wenn die Mehrheit für den Punkt ist, stör ich mich auch nicht dran.

**Comment by caugner** [comment]
Ohne vs. mit Punkt:

![grafik](https://user-images.githubusercontent.com/495429/78765835-d1c3ba80-7988-11ea-911c-5402baa7038d.png)

**Comment by chnuessli** [comment]
Ich würde es mit Punkt schreiben, sieht fertiger aus.


Von: Claas Augner <notifications@github.com>
Gesendet: Mittwoch, 8. April 2020 11:06
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Logo (#21)


Ohne vs. mit Punkt:

[grafik]<https://user-images.githubusercontent.com/495429/78765835-d1c3ba80-7988-11ea-911c-5402baa7038d.png>

**Comment by caugner** [comment]
Ich bin persönlich auch ein Fan von Punkten und stimme daher Christian zu.

**Wenn es bis 13 Uhr keine Einwände gibt**, leite ich folgenden Entwurf an das frz. Team weiter:
![grafik](https://user-images.githubusercontent.com/495429/78769434-a7c0c700-798d-11ea-9b26-7b8c1e8b6b15.png)

**Comment by jens1o** [comment]
Ha! Überpünktlich. 😝 

Ich finde das auch gut so!

**Comment by caugner** [comment]
**Entscheidung**: https://github.com/bleibtoffen/caresteouvert-de/issues/21#issuecomment-610858518
