### ISSUE TITLE
🇩🇪 DE: Kategorien festlegen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#22]
siehe: https://github.com/caugner/caresteouvert-de/blob/master/kategorien.md

**Vorlage** (Frankreich):

![image](https://user-images.githubusercontent.com/495429/78512028-8a2f0a00-77a1-11ea-8ca2-3bbc22f52f6e.png)

**Comment by caugner** [comment]
Mögliche Anpassungen:
* Drogerien und Sanitätshäuser (inkl. Hörgeräteakustiker und Optiker) könnten eine eigene Kategorie bekommen.
* Tabakwaren und Bestatter sind mglw. nicht nötig.

**Comment by hbruch** [comment]
Bestatter werden ab dem Moment einer höheren Mortalität sinnvoll. 

Die [Vorfilterung für Restaurants etc. auf solche mit Lieferdienst ](https://github.com/osmontrouge/caresteouvert/blob/master/categories.json#L171) halte ich für zu restriktiv, da somit viele, die nun neu einen Lieferdienst anbieten, gar nicht in der Karte erscheinen.

Grundsätzliche Frage: Wie erfolgt eine Anpassung? Zur Zeit gilt die gesamte Datei für alle Länder, ist eine Lokalisierung bereits in Arbeit?

**Comment by caugner** [comment]
Danke für das Feedback.

> Bestatter werden ab dem Moment einer höheren Mortalität sinnvoll.

"Bestatter" waren bis vor kurzem eine eigene Kategorie und wurden nun in "Geschäfte" verschoben:
https://github.com/osmontrouge/caresteouvert/commit/085739774b31242cdfd485fce77c212f2541efea

(Es ist grundsätzlich angedacht, die Kategorien-Auswahl dahingehend zu bessern, dass auch Unterkategorien ausgewählt werden können.)

> Die Vorfilterung für Restaurants etc. auf solche mit Lieferdienst halte ich für zu restriktiv

Ich persönlich bin ganz bei dir, das französische Team sieht es leider etwas anders. Dennoch werde ich es bei Gelegenheit noch einmal anregen.

Zu beachten ist, dass die Karte unübersichtlich werden würde, wenn auf einmal alle Restaurants hinzukämen. Um auch Restaurants ohne bereits definierten Lieferdienst anzuzeigen, müsste es ein Feature geben, diese nur bei Bedarf anzuzeigen (damit ein Restaurant die Information selbst ergänzen kann). Dieses Feature gibt es momentan aber leider noch nicht.

> Grundsätzliche Frage: Wie erfolgt eine Anpassung? Zur Zeit gilt die gesamte Datei für alle Länder, ist eine Lokalisierung bereits in Arbeit?

Die Kategorien können grundsätzlich je Land angepasst werden, die Reihenfolge nicht unbedingt. In DACH werden beispielsweise Drogeriemärkte schon als eigene Kategorie angezeigt, während sie in Frankreich (da unüblich) eine Unterkategorie von "Geschäfte" sind.

Theoretisch ginge auch eine Anpassung auf Bundesland-Ebene (z.B. sind Baumärkte in Mecklenburg-Vorpommern nur für Gewerbe offen), das wurde zumindest bei der Implementierung grundsätzlich berücksichtigt. Allerdings weiß ich nicht, ob das in der Praxis auch wirklich reibungslos funktioniert, und würde versuchen, darauf zu verzichten. Es ist immer ein Trade-off zwischen Aufwand/Komplexität und Nutzen.

**Comment by caugner** [comment]
Die Kategorien haben sich inzwischen geändert und die Hauptkategorien sind allgemeiner, sodass die Notwendigkeit von Anpassungen vielleicht gar nicht mehr besteht. Daher schließe ich das Issue erstmal.
