### ISSUE TITLE
Blog: Artikel "Über" übersetzen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#25]
Quelle: https://blog.caresteouvert.fr/about/

Idealerweise direkt als HTML hier: https://github.com/caugner/caresteouvert-de/new/master/?filename=blog/ueber/index.html

**Comment by caugner** [comment]
@ChristineKarch Falls es dir passt, kannst du dir das Issue einfach selbst zuweisen.

**Comment by ChristineKarch** [comment]
Wer kommt da ins Team rein? Die Franzosen uebernehmen?

**Comment by caugner** [comment]
> Wer kommt da ins Team rein? Die Franzosen uebernehmen?

Ja, die würde ich erst einmal so übernehmen.

**Comment by ChristineKarch** [comment]
Es sollte nochmal jeder beim Abschnitt Team drüber gehen, ob es ihm passt was da steht. 

https://github.com/caugner/caresteouvert-de/blob/master/blog/ueber/index.html

@datendelphin @giggls @caugner und falls ich jemanden vergessen habe .... !

**Comment by caugner** [comment]
Mir passt's.

@jens1o Magst du mit Vor- und Nachnamen dort auftauchen? Ggf. mit deinem Twitter-Handle?

**Comment by jens1o** [comment]
Ja, bitte Jens Hausdorf und dann unter Twitter als `@jens1o`.

**Comment by ChristineKarch** [comment]
> Ja, bitte Jens Hausdorf und dann unter Twitter als `@jens1o`.
done

**Comment by jens1o** [comment]
Danke! :)
