### ISSUE TITLE
Suchdienst auf der Karte

### ISSUE THREAD

**Issue by ChristineKarch** [bleibtoffen/bleibtoffen#26]
carestouvert verwendet einen Suchdienst, der für Deutschland nicht geeignet ist. Da sollte man in der deutschen Version etwas anderes einbauen.

**Comment by caugner** [comment]
Inwiefern ist der Suchdienst nicht geeignet?

**Comment by ChristineKarch** [comment]
Wenn ich eine deutsche Stadt eingebe, wird sie nicht gefunden. Das liegt daran, das der Suchdienst in einer rein französischen Datenbank sucht.

**Comment by caugner** [comment]
Ich bin mir ziemlich sicher, dass das französische Team bei der Ausweitung der Datenbasis auch den Suchdienst berücksichtigen und entsprechend erweitern wird. Möglicherweise kommt sogar beides aus der gleichen Datenbank, da bin ich mir nicht ganz sicher.

**Comment by caugner** [comment]
Kann inzwischen bestätigen, dass der Suchdienst bei der Erweiterung berücksichtigt wird:
https://github.com/osmontrouge/caresteouvert/commit/1b7edc4a5555aa6504f463da692932c778173bc2
