### ISSUE TITLE
Wiki-Seiten übersetzen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#3]
* [Key:opening_hours:covid19](https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19)

**Comment by caugner** [comment]
@giggls Habe dich entsprechend [deines Kommentars](https://github.com/caugner/caresteouvert-de/issues/2#issuecomment-608739432) nun diesem Ticket zugeordnet.

**Comment by giggls** [comment]
Morgen mal schaun...

**Comment by datendelphin** [comment]
übersetzt
https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours:covid19

**Comment by caugner** [comment]
Danke!

@giggls Könntest du die Seite noch einmal korrekturlesen?

**Comment by jens1o** [comment]
Sieht gut aus für mich.

**Comment by caugner** [comment]
Super, danke @datendelphin und @jens1o!
