### ISSUE TITLE
🇨🇭 CH: Handelsketten erfassen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#30]
**Was?** Schweizer Handelsketten erfassen, die in der [ketten.csv](https://github.com/caugner/caresteouvert-de/blob/master/ketten.csv) noch fehlen.

**Wie?** siehe [README](https://github.com/caugner/caresteouvert-de#handelsketten)

Bitte im Commit/PR dieses Issue erwähnen: #30

**Comment by chnuessli** [comment]
Ich habe Schweizer Ketten hinzugefügt.

**Comment by chnuessli** [comment]
Wird das CSV laufen eingelesen?

**Comment by caugner** [comment]
> Wird das CSV laufen eingelesen?

Jein, ich übertrage regelmäßig von hier in das Repository https://github.com/PanierAvide/Covid_enseignes, um dem französischen Kollegen die Arbeit zu erleichtern, vgl.: https://github.com/PanierAvide/Covid_enseignes/commit/14948016ebe57562c536c0b6e3dcec1ce568a8ba

**Comment by chnuessli** [comment]
Okay, hab noch ein Update auf ketten.csv gemacht.

**Comment by caugner** [comment]
Die Zeile 12 scheint die falsche Anzahl an Zeichen zu haben, kannst du das korrigieren?

![grafik](https://user-images.githubusercontent.com/495429/78909798-50e9e900-7a84-11ea-850d-6c0761bcf833.png)

**Comment by chnuessli** [comment]
Fixed line 12 #33

**Comment by caugner** [comment]
Hier ist eine aktuelle Statistik für die Schweiz, Anzahl der Ort je Handelskette mit Öffnungsstatus:

- [x] Coop (`open` x 308)
- [x] Migros (`open` x 297)
- [x] Avia (`unknown` x 233)
- [x] Shell (`unknown` x 207)
- [x] BP (`unknown` x 207)
- [x] McDonald's (`unknown` x 159)
- [x] Denner (`open` x 153)
- [x] Agrola (`unknown` x 140)
- [x] Valora (`unknown` x 133)
- [x] Migrol (`unknown` x 127)
- [x] Raiffeisen (`partial` x 119)
- [x] Tamoil (`unknown` x 117)
- [x] UBS (`partial` x 111)
- [x] Volg (`open` x 98)
- [x] Die Post (`unknown` x 94)
- [x] Die Schweizerische Post AG (`unknown` x 87)
- [x] Migrolino (`unknown` x 83)
- [x] Agip (`unknown` x 70)
- [x] Coop Genossenschaft (`unknown` x 67)
- [x] Eni (`unknown` x 61)
- [x] Socar (`unknown` x 61)
- [x] k kiosk (`unknown` x 53)
- [ ] BEBECO (`open` x 50)
- [x] Credit Suisse (`unknown` x 45)
- [x] AVIA (`unknown` x 44)
- [x] La Poste (`unknown` x 44)
- [x] Aldi (`open` x 41)
- [x] Spar (`open` x 41)
- [x] Coop Pronto (`unknown` x 40)
- [x] ZKB (`unknown` x 36)
- [x] La Posta (`unknown` x 35)
- [x] Rotpunkt Apotheke (`unknown` x 33)
- [x] POST CH AG (`unknown` x 33)
- [x] Esso (`unknown` x 30)
- [x] Raiffeisenbank (`unknown` x 30)
- [x] Burger King (`unknown` x 29)
- [x] Landi (`partial` x 29)
- [x] Avia (`open` x 28)
- [x] Post (`open` x 28)
- [x] Lidl (`open` x 26)
- [ ] Die Schweizerische Post (`unknown` x 26)
- [ ] Ruedi Rüssel (`unknown` x 25)
- [ ] BEBECO (`unknown` x 23)
- [x] Swisscom (`unknown` x 22)
- [x] Genossenschaft Migros Zürich (`unknown` x 21)
- [ ] Independent (`unknown` x 21)

(Source: https://github.com/PanierAvide/Covid_enseignes/issues/78#issuecomment-611597842)

**Comment by caugner** [comment]
Aktueller Stand ist gemergt: https://github.com/PanierAvide/Covid_enseignes/pull/81

@chnuessli Hast du die Zugriffsrechte, um Punkte in meiner Nachricht als erledigt zu markieren?

**Comment by das-g** [comment]
Hmm ... momentan werden auch melectronics-Filialen (z.b. [in Steinhausen](https://www.openstreetmap.org/way/737021556) und [in Rapperswil SG](https://www.openstreetmap.org/node/6019343943)) als offen angezeigt, vermutlich, weil die `operator=Migros` haben. Die sind als Elektronik-Fachmärkte aber geschlossen, auch wenn sie zum Migros-Konzern gehören.

Ähnliches gilt vermutlich für andere Fachmarkt-Brands der Migros. Nur die Migros-_Supermärkte_ sind offen, die diversen Fachmarkt-Ketten aber nicht.

**Comment by caugner** [comment]
> Hmm ... momentan werden auch melectronics-Filialen (z.b. in Steinhausen und in Rapperswil SG) als offen angezeigt, vermutlich

@das-g Danke für den Hinweis. Hättest du die Direktlinks zu den beiden Beispielen in bleibtoffen.ch? Dann kann ich es mir einmal anschauen.

**Comment by chnuessli** [comment]
Vermutlich dieselbe wikidata id?

**Comment by datendelphin** [comment]
geschlossen: https://www.bleibtoffen.ch/@47.191919,8.477930,17.75/place/w60988471
https://www.bleibtoffen.ch/@47.191919,8.477930,17.75/place/w737021556

Ich denke Elektronik und Garten sollte nicht angezeigt werden

**Comment by datendelphin** [comment]
> Vermutlich dieselbe wikidata id?

Es ist keine Wikidata id eingetragen

**Comment by sovereign-ch** [comment]
Fakt ist, die meisten POI haben weder 'brand', noch 'wikidata' eingetragen, da dies "so ein iD-Ding" war, sprich die meisten JOSM presets kein Feld dafür haben. Es erschien auch etwas sinnfrei brand="Migros" einzutragen, wenn ohnehin nur name="Migros" dastand.

Da ich kaum sämtliche Standorte über Nacht anpassen kann, bräuchte es einige Ergänzungen. Die einfachste wäre zur Zeit ein default 'closed' für electronics, doityourself, garden_center, furniture in der Schweiz. Die Landi müsste man entsprechend wieder mit 'partial' freischalten (rächt sich jetzt, dass man dies nicht vereinheitlicht hat). BTW sind Coop B+H, Migros Do it + Garden, Obi, Jumbo, Bauhaus, und Hornbach entgegen dem CSV _geschlossen_.

**Comment by chnuessli** [comment]
> Aktueller Stand ist gemergt: [PanierAvide/Covid_enseignes#81](https://github.com/PanierAvide/Covid_enseignes/pull/81)
> 
> @chnuessli Hast du die Zugriffsrechte, um Punkte in meiner Nachricht als erledigt zu markieren?

Habe Punkte die ich eingetragen habe als erledigt markiert.

**Comment by caugner** [comment]
> Fakt ist, die meisten POI haben weder 'brand', noch 'wikidata' eingetragen, da dies "so ein iD-Ding" war, sprich die meisten JOSM presets kein Feld dafür haben. Es erschien auch etwas sinnfrei brand="Migros" einzutragen, wenn ohnehin nur name="Migros" dastand.

In der Tat scheint CRO statt `brand` ersatzweise auch das Feld `operator` zu verwenden: https://github.com/osmontrouge/caresteouvert/blob/234df960067a270a52f4bfa35f12dc7877f3c38d/db/update_poi.sql#L96

Allerdings bin ich überrascht, dass [die Migros-Regel](https://github.com/PanierAvide/Covid_enseignes/blob/8317d227e3d6b576dbe79b380fcfd5c497d4353f/rules.csv#L54) hier angewendet wird, denn die Regel gilt eigentlich nur für `supermarket`.

Dazu habe ich nun ein Issue erstellt: #292

> Die einfachste wäre zur Zeit ein default 'closed' für electronics, doityourself, garden_center, furniture in der Schweiz. 

Kategorien lassen sich derzeit leider nicht auf "closed" setzen, sondern lediglich ausblenden. Ich habe das Feature jedoch angeregt: https://github.com/osmontrouge/caresteouvert/issues/291

> BTW sind Coop B+H, Migros Do it + Garden, Obi, Jumbo, Bauhaus, und Hornbach entgegen dem CSV geschlossen.

~~Könntest du ein PR erstellen mit diesen Änderungen?~~ (**Update**: Doch nicht, siehe Folgekommentar.)

**Comment by chnuessli** [comment]
> BTW sind Coop B+H, Migros Do it + Garden, Obi, Jumbo, Bauhaus, und Hornbach entgegen dem CSV _geschlossen_.

Nicht unbedingt. Ein Blick auf die Webseiten zeigt, dass die meisten einfach über Online-Shop und Take-Away fungieren. Z.B Landi operiert so und die meisten GartenCenter auch. Deswegen als Partial oder Open, je nachdem was auf der Webseite zu finden ist.

Es wird mittlerweile klar wieviele unterschiedliche Schreibweisen in der Schweiz heissen, zwei Beispiele:
- ZKB & Zürcher Kantonalbank
- Migros & Genossenschaft Migros
Wird vermutlich extrem schwer alle Schreibweisen in OSM irgendwie abzudecken.

**Comment by caugner** [comment]
> Es wird mittlerweile klar wieviele unterschiedliche Schreibweisen in der Schweiz heissen, zwei Beispiele:

Sofern `brand:wikidata` gesetzt ist, kein Problem. Eventuell ein guter Zeitpunkt, das zu ergänzen?

**Comment by caugner** [comment]
In https://github.com/osmontrouge/caresteouvert/issues/292 habe ich nun die Erklärung erhalten: Die `category`-Spalte in der `rules.csv` ist bewusst nur informativ, weil ansonsten für Marken mit verschiedenen Arten von Geschäften mehrere Regeln erforderlich wären.

Wenn in der Schweiz alle Elektronikmärkte geschlossen sind, wäre derzeit die einzige Lösung, die Geschäfte auf der Karte auszublenden. Wenn lediglich alle "melectronics"-Filialen geschlossen sind, würde eine zusätzliche Regel für diese "Kette" genügen.

**Comment by das-g** [comment]
> Wenn in der Schweiz alle Elektronikmärkte geschlossen sind, wäre derzeit die einzige Lösung, die Geschäfte auf der Karte auszublenden. Wenn lediglich alle "melectronics"-Filialen geschlossen sind, würde eine zusätzliche Regel für diese "Kette" genügen.

Meines Wissens sind alle Elektronikmärkte geschlossen. Nur Läden mit Produkten des täglichen Bedarfs dürfen öffnen.

**Comment by datendelphin** [comment]
Ich würde eher keine massen edits machen mit wikidata-ids. Das wurde immer wieder mal gemacht und das hat die community genervt.

**Comment by datendelphin** [comment]
Liste abgearbeitet in 6e7c509dba5

**Comment by datendelphin** [comment]
BEBECO sind Tankstellen ausschliesslich für die Armee

**Comment by caugner** [comment]
> Liste abgearbeitet in 6e7c509

Saubere Leistung! :rocket: 

Habe die Updates schon in [den aktuellen PR](https://github.com/PanierAvide/Covid_enseignes/pull/84) übernommen.

Damit können wir dieses Ticket eigentlich schließen, oder?

**Comment by datendelphin** [comment]
Ja machen wir doch das :smile:

**Comment by chnuessli** [comment]
Sehr cool!!!! 👍🏼💪🏼 Danke euch beiden

Freundliche Grüsse

Christian Nüssli
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Sunday, April 12, 2020 9:41:32 PM
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Assign <assign@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] 🇨🇭 CH: Handelsketten erfassen (#30)


Assigned #30<https://github.com/bleibtoffen/bleibtoffen/issues/30> to @chnuessli<https://github.com/chnuessli>.
