### ISSUE TITLE
Lieferdienste Restaurants

### ISSUE THREAD

**Issue by ChristineKarch** [bleibtoffen/bleibtoffen#34]
Bei uns haben natürlich die Restaurants geschlossen, aber nicht wenige bieten Lieferdienst. Ich hätte jetzt erwartet, dass da ein grauer Punkt in der Karte ist, den ich dann "grün machen" kann. 

Klammern wir Restaurants komplett aus, oder check ich es nur nicht?

(bitte closen, wenn ich da was jetzt verpeilt hab)

**Comment by ChristineKarch** [comment]
(ich hab jetzt mal auf der frz. Liste nachgefragt, ich melde mich dann mit der Antwort)

**Comment by ChristineKarch** [comment]
https://github.com/osmontrouge/caresteouvert/issues/138

**Comment by caugner** [comment]
Genau, Restaurants mit `takeaway=yes|only` bzw. `delivery=yes|only` werden inzwischen angezeigt.

Einziger Haken: Restaurants, die *neuerdings* Abholung oder Lieferung anbieten, können nicht über die CRO-Seite erfasst werden, sondern nur direkt in Restaurant.
