### ISSUE TITLE
Anleitung: Hinweise bearbeiten

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#35]
(Wenn du Fragen zu dieser Anleitung hast, schreibe bitte unten einen Kommentar.)

Hintergrund:
1. Bei Meldungen können **Zusätzliche wichtige Angaben (optional)** gemacht werden:
  ![grafik](https://user-images.githubusercontent.com/495429/78888904-e6748100-7a62-11ea-87da-84a87a4ded8e.png)
2. Beispiele:
   * Ort existiert nicht mehr
   * Ort heißt jetzt anders
   * Ort hat zusätzliche Einschränkungen (z.B. nur bestimmte Dienstleistungen).
1. Meldungen **ohne** *zusätzliche Angaben* werden **automatisch** in OSM übernommen. (Es wird keine Noitz erstellt.)
2. Meldungen **mit** *zusätzlichen Angaben* werden **nicht** automatisch in OSM übernommen. **Stattdessen  wird eine Notiz erstellt**, die **manuell** bearbeitet werden muss.

Voraussetzungen:
1. OpenStreetMap-Konto registriert: https://www.openstreetmap.org/user/new
2. JOSM installiert: https://josm.openstreetmap.de/
3. OSM-Konto in JOSM eingerichtet.

Empfohlener Workflow:
1. NotesReview aufrufen: https://ent8r.github.io/NotesReview/
1. Auf "Anmelden" klicken:
  ![grafik](https://user-images.githubusercontent.com/495429/78700113-3b9a8080-7905-11ea-8346-df7d01cd297c.png)
1. Auf "Zugriff gewähren" klicken:
  ![grafik](https://user-images.githubusercontent.com/495429/78700190-5d940300-7905-11ea-9e00-d34a84c4f87d.png)
1. Als Abfrage: `#caresteouvert` eingeben (bzw. `#caresteouvertDE` oder `#caresteouvertCH` oder `#caresteouvertAT`).
1. Die Einstellungen rechts oben öffnen:
  ![grafik](https://user-images.githubusercontent.com/495429/78699582-6932fa00-7904-11ea-8fcd-8e40da3329cf.png)
1. In den Einstellungen "JOSM" aktivieren:
  ![grafik](https://user-images.githubusercontent.com/495429/78699676-9089c700-7904-11ea-84ad-9b8b93fdcfe4.png)
1. Den Hinweis lesen und das Objekt in JOSM öffnen:
   ![grafik](https://user-images.githubusercontent.com/495429/78888635-52a2b500-7a62-11ea-83b1-a02ea027d408.png)
1. In JOSM *zum einen* die konkreten Änderungen übernehmen (**Tipp**: Key/Value-Zeilen markieren, kopieren und mit <kbd>Strg</kbd> + <kbd>V</kbd> in JOSM ans Objekt einfügen) und *zum anderen* die abstrakten Hinweise aus dem Freifeld-Kommentar darüber umsetzen.
1. Änderung hochladen und dabei die Hinweis-URL (Link "OSM" in NotesReview) als `source` angeben.
1. Anschließend die Notiz als erledigt markieren, entweder in JOSM oder in NotesReview.

**Comment by ChristineKarch** [comment]
Verstehe ich das richtig: Das ist der Workflow um die Daten der Mitmachern von "Bleibt Offen" nach OSM zu übernehmen? (also nicht wirklich ein Issue sondern mehr das was wir jetzt langfristig machen?)

**Comment by caugner** [comment]
> Das ist der Workflow um die Daten der Mitmachern von "Bleibt Offen" nach OSM zu übernehmen?

Jein, habe gerade noch einmal nachgefragt:

1. Meldungen **ohne** Anmerkung werden **automatisch** in OSM übernommen. (Es wird keine Noitz erstellt.)
2. Meldungen **mit** Anmerkung werden **nicht** automatisch in OSM übernommen. **Stattdessen**  wird eine Notiz erstellt, die **manuell** bearbeitet werden muss.

Das hatte ich mir auch selbst anders vorgestellt bzw. verstanden. Daher muss ich auch den Punkt 7 oben noch einmal überarbeiten (**Update**: Erledigt.).

**Comment by caugner** [comment]
@ChristineKarch Ich habe die Anleitung aktualisiert bzw. erweitert und blende daher nun unsere Kommentare aus.

**Comment by caugner** [comment]
Es gibt inzwischen auch einen [französischen Blog-Artikel](https://blog.caresteouvert.fr/contributeurs-openstreetmap-comment-traiter-les-notes-caresteouvert/) dazu, den wir in #61 übersetzen.

**Comment by caugner** [comment]
Es gibt jetzt eine deutsche Übersetzung des französischen Blog-Artikels:
https://www.bleibtoffen.org/2020/04/18/hinweise-bearbeiten.html

Daher schließe ich dieses Issue.
