### ISSUE TITLE
URL's in allen Blogartikeln anpassen

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#36]
Sollten wir nicht alle URL's in den HTML Datein noch anpassen auf die DE / AT / CH?
Oder belassen wir diese so?

**Comment by caugner** [comment]
Nach letztem Stand arbeitet das französische Team gerade daran, die übersetzten Einträge in ihr Blog zu übernehmen. Solange würde ich noch abwarten.

Meine Idee war, `bleibtoffen.org` über GitHub Pages mit `bleibtoffen/bleibtoffen-org` zu verknüpfen. Dann könnten wir das selbständig ändern. Können wir aber auch später noch nachholen.

Die Links aus der Oberfläche werden im französischen Repository in der `config.json` festgelegt: https://github.com/osmontrouge/caresteouvert/blob/master/config.json

**Comment by chnuessli** [comment]
Momentan noch Status Quo. Warten wir mal noch ab.

**Comment by caugner** [comment]
CRO beabsichtigt weiterhin einen multilingualen WordPress-Blog, dann würden wir `blog.bleibtoffen.org` per `CNAME` auf `blog.caresteouvert.fr` setzen. Davon unabhängig können wir ja trotzdem `www.bleibtoffen.org` via GitHub Pages als Einstiegsseite mit Landesauswahl erstellen, wo wir ggf. eigenen Content problemlos unterbringen können.

**Comment by caugner** [comment]
Siehe #49.
