### ISSUE TITLE
1. Pressemitteilung verfassen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#37]

**Comment by chnuessli** [comment]
Wenn du willst kann ich die Medien in CH bedienen. Kann mich mit @datendelphin abgleichen welche wir dann bedienen möchten.

**Comment by caugner** [comment]
Das französische Team hat ein Pressedossier (auf Französisch) vorbereitet, das wir vermutlich als Vorlage verwenden können.

**Comment by ChristineKarch** [comment]
Eine Pressemitteilung kann auch hier hin geschickt werden: presseteam@lists.openstreetmap.de

**Comment by caugner** [comment]
> Eine Pressemitteilung kann auch hier hin geschickt werden: presseteam@lists.openstreetmap.de

Ah, und das Presseteam leitet es dann an Pressekontakte weiter?

**Comment by Nakaner** [comment]
> Ah, und das Presseteam leitet es dann an Pressekontakte weiter?

Das hast du richtig geraten. Wir schauen uns den Text aber vor dem Weiterleiten nochmal an. (Ich bin im Presseteam)

**Comment by caugner** [comment]
**Kurzes Update**: Ursprünglich wollte ich die Pressemitteilung schon längst geschrieben haben. Heute werde ich leider nicht dazu kommen, aber hoffentlich morgen.

Das französische Team feilt noch an ihrer Pressemappe.

Je früher wir an die Presse treten, desto besser, andererseits sind ja jetzt Feiertage, was die Erfassung von Öffnungszeiten etwas schwieriger gestaltet.

**Comment by caugner** [comment]
@Nakaner Wir haben nun zwei Texte:

* Eine kurze Zusammenfassung: https://www.bleibtoffen.org/presse.html
* Eine ausführliche Pressemitteilung: https://www.bleibtoffen.org/2020/04/12/pressemitteilung.html

In welcher Form sollten wir welchen der Texte am besten an das Presseteam schicken? Als Text oder als PDF?

**Comment by Nakaner** [comment]
Reinen Text bzw. Markdown bittet.

Mein Angebot war eigentlich gedacht, dass ihr den Text schickt, bevor er veröffentlicht wird (der Pull-Request gemergt wird).

**Comment by caugner** [comment]
@Nakaner Tut mir leid, das hatte ich falsch verstanden. Wir haben die Pressemitteilung aber, abgesehen von der (bisher sicher wenig beachteten) noch nicht verbreitet.

Inzwischen habe ich eine E-Mail ans Presseteam geschickt, die wartet allerdings noch auf Genehmigung.

@chnuessli @datendelphin Ihr verteilt die Meldung in der Schweiz, oder?

Was Österreich betrifft, so würde ich „Bleibt offen“ dort erst einmal nicht bewerben, es sei denn es finden sich Aktive aus der Community, die das übernehmen wollen. Möglicherweise ist das Interesse geringer, weil eine Aufhebung der Ausgangsgeschränkungen angekündigt wurde. Ich kann mir aber gut vorstellen, dass früher später wieder eine neue Ausgangsbeschränkung kommt.

**Comment by chnuessli** [comment]
Ich habe die Mitteilung heute an alle grossen Medienhäuser in der Schweiz gesendet. Die Resonanz ist aber noch = Null.

Freundliche Grüsse

Christian Nüssli
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Monday, April 13, 2020 3:25:49 PM
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] 1. Pressemitteilung verfassen (#37)


@Nakaner<https://github.com/Nakaner> Tut mir leid, das hatte ich falsch verstanden. Wir haben die Pressemitteilung aber, abgesehen von der (bisher sicher wenig beachteten) noch nicht verbreitet.

Inzwischen habe ich eine E-Mail ans Presseteam geschickt, die wartet allerdings noch auf Genehmigung.

@chnuessli<https://github.com/chnuessli> @datendelphin<https://github.com/datendelphin> Ihr verteilt die Meldung in der Schweiz, oder?

Was Österreich betrifft, so würde ich „Bleibt offen“ dort erst einmal nicht bewerben, es sei denn es finden sich Aktive aus der Community, die das übernehmen wollen. Möglicherweise ist das Interesse geringer, weil eine Aufhebung der Ausgangsgeschränkungen angekündigt wurde. Ich kann mir aber gut vorstellen, dass früher später wieder eine neue Ausgangsbeschränkung kommt.

**Comment by caugner** [comment]
Alles klar, danke! Im Zweifel liegt die geringe Resonanz an der Länge und geht auf meine Kappe. :wink:

**Comment by chnuessli** [comment]
Gar nicht, die Mitteilung ist mMn gut. Evtl, gibts für die Medien im Zusammenhang mit Covid einfach reissenderes. Städte & Twitter ist evtl. Gar keine schlechte Idee.

Freundliche Grüsse

Christian Nüssli
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Monday, April 13, 2020 3:29:34 PM
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] 1. Pressemitteilung verfassen (#37)


Alles klar, danke! Im Zweifel liegt die geringe Resonanz an der Länge und geht auf meine Kappe. 😉

**Comment by datendelphin** [comment]
Danke @chnuessli 
Das haben wir ja leider etwas erwartet, da einige bereits eigene Angebote in dem Bereich haben.

Auf https://twitter.com/SwissOSM haben wir auch mal einen tweet gemacht. Blogpost auf sosm.ch fehlt noch.

**Comment by caugner** [comment]
@Nakaner Ist von unserer Seite noch etwas zu tun? Soweit ich sehe, steht meine E-Mail an das Presseteam noch auf "Genehmigung erforderlich".
