### ISSUE TITLE
Impressum übersetzen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#38]
Quelle: https://blog.caresteouvert.fr/mentions-legales/

Ziel: https://github.com/caugner/caresteouvert-de/new/master/?filename=blog/impressum/index.html

**Comment by ChristineKarch** [comment]
https://github.com/bleibtoffen/caresteouvert-de/blob/master/blog/impressum/index.html

Bitte nochmal Korrektur lesen!

**Comment by caugner** [comment]
@jens1o Hättest du Zeit?

**Comment by chnuessli** [comment]
Wenn ihr möchtet kann ich mich dem Morgen annehmen.

Gruss Christian


Von: Claas Augner <notifications@github.com>
Gesendet: Mittwoch, 8. April 2020 16:21
An: bleibtoffen/caresteouvert-de <caresteouvert-de@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [bleibtoffen/caresteouvert-de] Impressum übersetzen (#38)


@jens1o<https://github.com/jens1o> Hättest du Zeit?

**Comment by caugner** [comment]
@chnuessli Gern!

**Comment by chnuessli** [comment]
Erledigt, nur kleine Typos gefunden, danke fürs Übersetzen

**Comment by jens1o** [comment]
LGTM.

**Comment by caugner** [comment]
Danke euch allen! :rocket:
