### ISSUE TITLE
laundry with r

### ISSUE THREAD

**Issue by Bibi56** [bleibtoffen/bleibtoffen#39]
In https://github.com/bleibtoffen/caresteouvert-de/blob/master/laender.md, steht `shop=laundy`. `shop=laundry` klingt besser ;-).
In `laender.csv` fehlt die Info. Ohne Tippfehler dann ;-)

**Comment by caugner** [comment]
Gut bemerkt!

Maßgeblich ist tatsächlich die `laender.csv`. Darin finde ich den Eintrag ohne Tippfehler:

https://github.com/bleibtoffen/caresteouvert-de/blob/60905d084ee18d5a26803e17b65fa17f8ee1648a/laender.csv#L33

**Comment by caugner** [comment]
@Bibi56 Wenn du magst, kannst du den Tippfehler gerne [hier](https://github.com/bleibtoffen/caresteouvert-de/edit/master/laender.md) korrigieren und im "Pull Request", der dann geöffnet wird, die Nummer `#39` erwähnen.

**Comment by Bibi56** [comment]
Getan! ;-)
