### ISSUE TITLE
Öffnungszeiten: Option "bleiben gleich" fehlt

### ISSUE THREAD

**Issue by ChristineKarch** [bleibtoffen/bleibtoffen#41]
Hier scheint die Möglichkeit zu fehlen, zu sagen dass die Öffnungszeiten gleich bleiben:

![screenshot-beinert](https://user-images.githubusercontent.com/15981021/78813150-e164f280-79cc-11ea-830e-79885f6644cc.png)

Habt ihr es selber schon mal ausprobiert? Ich meine letzte Woche hab ich einfach "same" auswaehlen koennen, oder irgendwas aehnliches ...

**Comment by caugner** [comment]
Hättest du einen Link?

**Comment by ChristineKarch** [comment]
Das laesst sich per Link nicht "sehen", da man dazu erst auf den grauen Boebbel klicken muss, dann geht rechts das Fenster fuers Editieren auf. Es gilt fuer jeden grauen Boebbel. Und exemplarisch hab ich den Screenshot hier an dieser Geo-Koordinate geoeffnet:

https://www.bleibtoffen.de/@48.564459,7.864718,19.34/place/w45570503

Aber ich glaube der Screenshot ist aussagekraeftiger als der Link.

**Comment by caugner** [comment]
> https://www.bleibtoffen.de/@48.564459,7.864718,19.34/place/w45570503

Zu dem Ort sind noch keine Öffnungszeiten erfasst, daher gibt es nicht die Abkürzung "wie immer". In diesen Fällen gibt es nach Eingabe der Öffnungszeiten eine entsprechende Checkbox.

**Allerdings** ist die Überschrift in diesem Fall eindeutig verwirrend.

Sollte also vielleicht eher heißen: `Wann hat dieser Ort geöffnet?`
Und bei vorhandenen Öffnungszeiten könnte dann die erste Option lauten: `Zu den üblichen Zeiten`.

**Comment by datendelphin** [comment]
Ja das ist so. Ich wollte diese Migros als "same" markieren, aber das kam dabei heraus: https://www.openstreetmap.org/way/609946515 nicht same sondern eine Kopie der öffnungszeiten

**Comment by ChristineKarch** [comment]
Ok, das ist verwirrend. Danke fuers Nachforschen! Wie waere es mit

"Welche Öffnungszeiten gelten jetzt?"

**Comment by ChristineKarch** [comment]
> Ja das ist so. Ich wollte diese Migros als "same" markieren, aber das kam dabei heraus: https://www.openstreetmap.org/way/609946515 nicht same sondern eine Kopie der öffnungszeiten

Das sieht so aus, als steht beim kopieren nur eine bestimmte Anzahl von Zeichen zur Verfügung ...? Bug-Report an die Franzosen?

**Comment by caugner** [comment]
> "Welche Öffnungszeiten gelten jetzt?"

Würde auch klappen. "Wann hat dieser Ort geöffnet?" wäre analog(er) zu "Ist dieser Ort weiterhin geöffnet?".

> Das sieht so aus, als steht beim kopieren nur eine bestimmte Anzahl von Zeichen zur Verfügung ...? Bug-Report an die Franzosen?

Wofür steht `PH`? Daran liegt es vermutlich. Ist aber in der Tat einen Bug-Report wert.

**Comment by datendelphin** [comment]
Aber ich will doch ein tag opening_hours:covid19=same, nicht eine Kopie der opening hours

PH steht für public holidays.

**Comment by caugner** [comment]
Erstellt ihr ein Issue im frz. Repository mit Verweis auf dieses Issue?

**Comment by caugner** [comment]
> "Welche Öffnungszeiten gelten jetzt?"

Habe es jetzt erst einmal zu `Wann hat dieser Ort geöffnet?` und `Zu den üblichen Zeiten` aktualisiert.

@ChristineKarch Für `Welche Öffnungszeiten gelten jetzt?` bräuchte ich noch eine korrespondierende Antwort statt `Zu den üblichen Zeiten`.

**Comment by caugner** [comment]
Die Änderungen sind bereits aktiv:

![image](https://user-images.githubusercontent.com/495429/78833842-d5d5f380-79ed-11ea-85fd-56c0d8f9bca8.png)

Ich schließe daher das Ticket erst einmal.
