### ISSUE TITLE
OpenStreetMap in den Twitter-Account

### ISSUE THREAD

**Issue by ChristineKarch** [bleibtoffen/bleibtoffen#42]
Aktuell haben wir diesen Text im Twitter-Profil:

> @caresteouvert
>  in deutscher Sprache. #StayHome
> 
> Eine kollaborative Karte der offenen Orte
> in Zeiten von COVID-19-Beschränkungen.

Wie kann man da auf nette Art und Weise noch das Wörtchen OpenStreetMap ergänzen? :)

**Comment by caugner** [comment]
> Wie kann man da auf nette Art und Weise noch das Wörtchen OpenStreetMap ergänzen? :)

Wie wäre es mit `Powered by @OpenStreetMap.`?

**Comment by caugner** [comment]
Verdammt, habe gerade das Konto abgeschossen, indem ich den heutigen Tag als Geburtstag eingetragen habe. Keine gute Idee!

**Comment by chnuessli** [comment]
Powered by OpenStreetMap-Community // @Openstreetmap

Sowas?

**Comment by caugner** [comment]
Da Twitter `@bleibtoffen` immer noch nicht entsperrt hat, habe ich jetzt einen neuen Account [@bleibtoffen_org](https://twitter.com/bleibtoffen_org) erstellt und OpenStreetMap in die Beschreibung aufgenommen.
