### ISSUE TITLE
Banner auf openstreetmap.de

### ISSUE THREAD

**Issue by ChristineKarch** [bleibtoffen/bleibtoffen#43]
Michael bietet an dass wir einen Banner auf openstreetmap.de haben duerfen. Wir sollen einen pull-request dafür machen. Für die Implementierung sollen wir alte Pull-Requests anschauen.

**Comment by caugner** [comment]
* Repository: https://github.com/fossgis/openstreetmap.de
* Beispiel: https://github.com/fossgis/openstreetmap.de/commit/c5720f9e3eab95f3d2dd9d25bde3c0053099a92c

**Comment by ChristineKarch** [comment]
@giggls Kannst du hier helfen?

**Comment by giggls** [comment]
Was genau soll ich tun?

**Comment by ChristineKarch** [comment]
> Michael bietet an dass wir einen Banner auf openstreetmap.de haben duerfen. Wir sollen einen pull-request dafür machen. Für die Implementierung sollen wir alte Pull-Requests anschauen.

@giggls

**Comment by giggls** [comment]
Ach so ich soll das machen. OK, ich kümmere mich.

**Comment by giggls** [comment]
Was soll denn im Banneer drinstehen?

**Comment by ChristineKarch** [comment]
Unser Logo mit einem Slogan darunter, so wie oben links auf:

https://www.bleibtoffen.de

Das reicht, oder?

**Comment by ChristineKarch** [comment]
Nee, reicht nicht, unbedingt noch das:

Powered by OpenStreetMap-Community // @openstreetmap

**Comment by giggls** [comment]
Ach so ich hätte jetzt schon auch einen Hilfsaufruf an Mapper zum tagging ergänzt.

**Comment by ChristineKarch** [comment]
Ja klar!

**Comment by giggls** [comment]
Alt:
``
OpenStreetMap feiert am 8./9. August 2019 seinen 15. Geburtstag.
<a href="https://wiki.openstreetmap.org/wiki/OpenStreetMap_15th_Anniversary_Birthday_party">Feiern Sie mit!</a>
``
Neu: ?

**Comment by caugner** [comment]
> Neu: ?

Ein passender Hinweis auf unser Projekt, nach deinem Gusto.

**Comment by ChristineKarch** [comment]
`<a href="https://www.bleibtoffen.de">Bleibt Offen</a> sammelt die Sonder-Öffnungszeiten mit speziellen <a href="https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours:covid19">Covid19-Tags</a> während der Covid19-Krise. Helft mit beim Mappen!`

**Comment by ChristineKarch** [comment]
oder so irgendwas :)

**Comment by giggls** [comment]
done.
https://github.com/fossgis/openstreetmap.de/commit/f58fa0fc6e2ff9ddd2daf0a5a77e5cd13cce1e56Pushed:

**Comment by giggls** [comment]
done.
https://github.com/fossgis/openstreetmap.de/commit/f58fa0fc6e2ff9ddd2daf0a5a77e5cd13cce1e56

**Comment by ChristineKarch** [comment]
Ich habs an Michael weitergeleitet, damit er es merged

**Comment by giggls** [comment]
Habs direkt commited hab Schreibrechte, wie ich grade gemerkt habe.

**Comment by giggls** [comment]
Ist live.
