### ISSUE TITLE
Titel der Seite "It remains open"

### ISSUE THREAD

**Issue by jens1o** [bleibtoffen/bleibtoffen#45]
Ist das Absicht? Oder fehlt hier noch die deutsche Übersetzung für das `<title>`-Tag?

**Comment by caugner** [comment]
**Erklärung**: Dein Browser ist auf Englisch und der `<title>` kommt derzeit aus dem Locale.

Dieses Verhalten könnte verbessert werden: https://github.com/osmontrouge/caresteouvert/issues/262

**Comment by jens1o** [comment]
Ah, das macht Sinn. Hab sonst alles auf Englisch, aber das war verwirrend für mich. Danke für die Erklärung. :)

**Comment by caugner** [comment]
@jens1o Kannst du bitte prüfen, ob der Titel für dich jetzt immer noch "It remains open" ist? Bei mir ist er jetzt unabhängig von der Sprache "Bleibt offen" (außer direkt beim Laden der Seite, da wird noch kurz "Ca reste ouvert" angezeigt).

**Comment by jens1o** [comment]
Am Anfang ist "Ca reste ouvert", aber dann "Bleibt offen" :)

**Comment by caugner** [comment]
Okay, dann schließe ich.

Das andere Problem wird durch https://github.com/osmontrouge/caresteouvert/issues/265 gelöst.
