### ISSUE TITLE
Links in externem Tab öffnen

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#47]
Wenn ich in der folgenden Ansicht einen Link klicke, öffnet es diesen in der gleichen Ansicht und meine Änderung wird verworfen. Evtl. mit den frz. Kollegen klären.
![image](https://user-images.githubusercontent.com/63254403/78888691-6cdc9300-7a62-11ea-861d-7307a3325f9d.png)

**Comment by caugner** [comment]
Beispiel-Link? (Bitte immer angeben.)

PS: Eigentlich müsste schon eine Warnung erscheinen: https://github.com/osmontrouge/caresteouvert/issues/241

**Comment by chnuessli** [comment]
Zum Beispiel hier: https://www.bleibtoffen.ch/@47.305608,8.758276,16.34/place/n3490785529

Wird aber bei allen Links die auf dem Overlay angezeigt werden gleich gehandhabt.

**Comment by caugner** [comment]
@chnuessli Und wo genau hast du hingeklickt?

Bei mir kommt z.B. beim Klick auf die Webseite eine Warnung:
![grafik](https://user-images.githubusercontent.com/495429/78898670-75d66000-7a74-11ea-9bc7-63af6243947e.png)

**Comment by chnuessli** [comment]
Die Warnung kommt bei mir auch im Bearbeitungsmodus. Wenn ich nur im View bin, dann werde ich direkt weitergeleitet und bin von «unserer» Seite weg.

**Comment by caugner** [comment]
> Wenn ich nur im View bin, dann werde ich direkt weitergeleitet und bin von «unserer» Seite weg.

Achso, verstehe, also wäre dein Vorschlag, Links generall in neuem Tab zu öffnen: `target="_blank"`. Wahrscheinlich wäre das insbesondere auch für Mobile Endgeräte sinnvoll. Ich erstelle ein Ticket im frz. Repo...

**Comment by chnuessli** [comment]
Aus Usability Gedanken sicher das Richtige, danke fürs Weiterleiten

**Comment by caugner** [comment]
@chnuessli Der Upstream-Bug wurde soeben behoben, was ich an deinem Beispiel-Link schnell nachvollziehen konnte (deswegen sind die konkreten Beispiele so wichtig).
