### ISSUE TITLE
Add amenity=cafe

### ISSUE THREAD

**Issue by giggls** [bleibtoffen/bleibtoffen#48]
Some coffee-shops have delivery and or takeaway services similar to restaurants but for cakes etc.

Example: https://ateliercafe.anaundanda.de/

**Comment by caugner** [comment]
@giggls CRO hat die Anforderung nun umgesetzt. Es dürfte jetzt noch ca. 1h dauern, bis die Cafés in der Karte erscheinen.

Kannst du dieses Ticket schließen, sobald du die Cafés in der Karte siehst?

**Comment by giggls** [comment]
Tut: https://www.bleibtoffen.de/@49.010948,8.393070,17.53/place/n6913996801
BTW. Banner auf http://openstreetmap.de ist jetzt auch Live.
