### ISSUE TITLE
Blog-Einträge in Markdown umwandeln

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#49]
1. Erstmal lokal hier in unserem Repository:
  * Blog-Verzeichnis aufrufen
  * Unterverzeichnigs aufrufen
  * `Create new file` => `index.md`
2. Später verschieben wir hierhin: https://github.com/osmontrouge/caresteouvert_blog

**Comment by chnuessli** [comment]
Kann ich Morgen angehen.

**Comment by chnuessli** [comment]
Erledigt in Commit: https://github.com/bleibtoffen/caresteouvert-de/commit/e1a005f7fc2a94bc01a290994165ce9424906aeb

Bitte noch kurz Kontrolle / Feedback an mich.

**Comment by chnuessli** [comment]
Done
