### ISSUE TITLE
Namensgebung

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#5]
Wie sollte die deutsche Version von "Ca reste ouvert" heißen?

**Comment by caugner** [comment]
Schon vergeben sind: [nochoffen](https://www.nochoffen.de/) und [wirhabenauf](https://wirhabenauf.de/)

Aber *bleibtauf* wäre noch verfügbar. Hatte auch an *offenoffen* gedacht.

**Comment by caugner** [comment]
@giggls @jens1o Was haltet ihr davon oder hättet ihr auch Vorschläge?

**Comment by giggls** [comment]
Ich finde diese nationalen Alleingänge eher nicht so gut.
Unter .org gäbe es noch geöffnet/geoeffnet.

**Comment by caugner** [comment]
> Ich finde diese nationalen Alleingänge eher nicht so gut.

Die Bedenken kann ich verstehen. Und tatsächlich ist mein letzter Stand, dass im Team über einen internationalen Namen nachgedacht wurde.

In Frankreich ist ein französischer Name wichtig für eine hohe Akzeptanz. Mit einem englischen Namen wäre die Webseite vermutlich kein Erfolg. Bei "ca reste ouvert" versteht man sofort den Zweck und den Bezug. Gleiches würde vermutlich für Italien und auch Spanien gelten.

Ein globales Rollout ist meines Wissens nicht direkt geplant, da das Wissen fehlt, welche Orte in welchen Ländern noch geöffnet sein dürfen.

Hättest du Vorschläge für eine internationale Benennung?

> Unter .org gäbe es noch geöffnet/geoeffnet.

Bei `geöffnet/geoeffnet.org` würde IMO der Bezug fehlen. Außerdem sähe ich Verwechslungsgefahr mit `geöffnet/geoeffnet.de`.

**Comment by caugner** [comment]
Habe gerade noch einmal gefragt und der internationale Name ist wohl bald gefunden.

Wahrscheinlich läuft es also darauf hinaus, dass Deutschland entweder zum Testen bereits vorab (unter der frz. Domain) oder dann mit dem internationalen Launch dazukommt.

Wir brauchen also für Deutschland keinen eigenen Namen zu finden.

**Comment by giggls** [comment]
Ich sagte ja bereits, dass ich <irgendwas>.openstreetmap.de und ggfs. Webspace problemlos einrichten kann.

**Comment by ChristineKarch** [comment]
(die Schweizer diskutieren gerade auch auf ihrem regional-chat dass sie das machen wollen)

**Comment by caugner** [comment]
> Ich sagte ja bereits, dass ich .openstreetmap.de und ggfs. Webspace problemlos einrichten kann.

Wenn wir bei der französischen Community einfach "aufspringen", hat das IMO den entscheidenden Vorteil, dass wir uns nicht selbst um Hosting und Update einer eigenständigen Instanz kümmern müssen. Die französische Instanz (demnächst wie gesagt unter internationalem Namen) wird kontinuierlich bei neuen Commits auf dem `master`-Branch automatisch aktualisiert.

Spricht aus deiner Sicht etwas dagegen, die französische Infrastruktur mitzunutzen?

Gegen eine Subdomain spricht aus meiner Sicht, dass die umständlich einzutippen und schwer zu merken ist, insbesondere für OSM-Neulinge.

> (die Schweizer diskutieren gerade auch auf ihrem regional-chat dass sie das machen wollen)

Sehr schön, vielleicht können wir ja D-A-CH zusammen launchen? In Wien gibt es möglicherweise auch Interessierte.

**Comment by ChristineKarch** [comment]
Ich bin da sehr dafür mit den Franzosen zusammenzugehen!
