### ISSUE TITLE
Elektronikgeschäfte ausblenden

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#50]
Laut unserer [laender.csv](https://github.com/bleibtoffen/caresteouvert-de/blob/master/laender.csv) sind Elektronikgeschäfte (`shop=electronics`) in DACH nicht geöffnet.

Siehe auch: https://github.com/bleibtoffen/caresteouvert-de/issues/30#issuecomment-612052594

**Comment by ChristineKarch** [comment]
Auch auf die Gefahr hin, dass ich jetzt alles durcheinanderbringe, aber da sind die Elektronikgeschäfte ein schönes Beispiel. Bei mir in der Region sind viele Geschäfte zwar offiziell geschlossen - wie auch die Elektronikgeschäfte. Haben aber Anzeigen in den Zeitungen, dass sie liefern. Sowohl Ketten als auch Einselhandel. Auch bei Restaurants ist das ja so!

Welches Konzept haben wir hierfür? Tagging ist klar (opening_hours:covid19 plus delivery:covid19 bzw auch takeaway:covid19).

**Comment by caugner** [comment]
> Bei mir in der Region sind viele Geschäfte zwar offiziell geschlossen - wie auch die Elektronikgeschäfte. Haben aber Anzeigen in den Zeitungen, dass sie liefern. Sowohl Ketten als auch Einselhandel. Auch bei Restaurants ist das ja so!

Sorry, dass ich da mit dem PR (inzwischen im "draft"-Status, wird also nicht gemergt) so vorgeprescht bin. Die Lieferung hatte ich ganz vergessen.

Idealerweise würde https://github.com/osmontrouge/caresteouvert/issues/291 das Problem lösen, dann könnten wir die analog zu Restaurants "global" (pro Land) als `opening_hours=closed` markieren und die User hätten trotzdem die Möglichkeit, sie ganz gezielt in BO einzublenden und zu melden, falls eine Lieferung oder Abholung möglich ist. Früher oder später wird das Feature wohl kommen. Bis dahin brauchen wir eine andere Lösung.

Hilfreich wäre es auch, wenn wir in den Regeln für Handelsketten auch `delivery` bzw. `takeaway` hinterlegen könnten. Insbesondere für große Ketten (z.B. Media Markt, Saturn) könnten wir dann `opening_hours=open` und `delivery=only` definieren.

Andererseits, und das spricht wohl gerade bei den Elektronikgeschäften *gegen* das Ausblenden, gibt es davon – im Gegensatz zu den Restaurants – nicht so viele, sodass die paar Elektronigeschäfte nicht stören sollte. Das ist vielleicht ein guter Grundsatz: "Seltene Geschäfte lieber anzeigen als ausblenden, auch wenn sie überwiegend geschlossen sind."

**Comment by caugner** [comment]
**Update**: Es werden künftig auch alle Restaurants und Imbisse ohne `delivery` bzw. `takeaway` angezeigt: https://github.com/osmontrouge/caresteouvert/commit/81f63b7e39a10d5cbb89cc3b616557c0c552851a

(Dauert noch ca. 1h, bis diese in der Karte sichtbar werden.)

**Comment by datendelphin** [comment]
Ich hab mit mal den Aktuellen Stand angesehen: es heisst bei Elektronik Geschäften immer noch: "Dieser Ort darf wahrscheinlich geöffnet bleiben." was für die Schweiz so gar nicht passt :) die dürfen ja nur noch online handel machen. Ich habe im csv mal melectronics und interdiscount ergänzt d1c57855b7, keine Ahnung, wann das upgedated wird, aber dann sollten wenigstens die hoffentlich rot angezeigt werden werden.

**Comment by caugner** [comment]
> es heisst bei Elektronik Geschäften immer noch: "Dieser Ort darf wahrscheinlich geöffnet bleiben." was für die Schweiz so gar nicht passt 

@datendelphin Finden wir eine bessere Formulierung, die für Orte, die gleichermaßen für Orte gilt, die uneingeschränkt geöffnet bleiben dürfen (Supermärkte) und eingeschränkte Orte (Elektronikmärkte, Restaurants) gilt?

Eventuell:

> Dieser Ort darf **möglicherweise** geöffnet bleiben.

**Comment by caugner** [comment]
In https://github.com/osmontrouge/caresteouvert/pull/329 schlage ich eine vorsichtigere Formulierung für das englische Original vor.

**Comment by caugner** [comment]
@ChristineKarch @datendelphin Seht ihr hier noch Handlungsbedarf? Wenn nicht, würde ich das Issue schließen.

**Comment by datendelphin** [comment]
Wenn es da keine bessere Lösung gibt (zusätzlicher Status darf wahrscheinlich nicht geöffnet sein, pro Land) mit vertretbarem Aufwand, ists halt so. kann man schliessen. Danke @caugner fürs Verhandeln in https://github.com/osmontrouge/caresteouvert/pull/329

**Comment by caugner** [comment]
Mit #89 wird die Möglichkeit geschaffen, pro Land zu definieren, was geöffnet sein darf bzw. nur bestimmte Dienstleistungen (delivery,takeaway) anbieten darf und was nicht.

**Comment by datendelphin** [comment]
Ah verstehe, da müssen wir noch etwas machen. Danke für die Erklärung

**Comment by chnuessli** [comment]
Dieser Task kann auch geschlossen werden oder?

**Comment by caugner** [comment]
@chnuessli Ich denke schon.
