### ISSUE TITLE
1. Pressemitteilung verbessern

### ISSUE THREAD

**Issue by datendelphin** [bleibtoffen/bleibtoffen#53]
Vorschlag für Verbesserungen:

Ansprechpartner auch in der Medienmitteilung erwähnen.
Ansprechpartner für die Schweiz (z.B. stefan keller oder mich)
Feedback vom sosm Kollegen: liest sich wie ein blog Artikel, sollte es aber nicht als Pressemitteilung:
* Titel kurz
* Lead der Aufmerksamkeit erzeugt
* Text, umgekehrte Pyramide, die Redaktionen kürzen von unten her

**Comment by caugner** [comment]
Danke für das ausführliche Feedback. :+1:

> Ansprechpartner auch in der Medienmitteilung erwähnen.

:+1: 

> Ansprechpartner für die Schweiz (z.B. stefan keller oder mich)

Sehr gern, mit welchen Kontaktdaten?

> Feedback vom sosm Kollegen: liest sich wie ein blog Artikel, sollte es aber nicht als Pressemitteilung:

Kann ich nachvollziehen.

Inzwischen habe ich auch das (sehr viel kürzere) französische Original gefunden:
https://www.caresteouvert.fr/pages/communique_presse.pdf

**Comment by datendelphin** [comment]
Ich würde auch noch Telefonnummern dazu schreiben, aber vielleicht nicht öffentlich, sondern nur in der Version, die an Presseleute gesendet wird. Ich hab mal etwas vorgeschlagen für Verbesserungen, ist aber noch nicht viel und noch nicht so gut

**Comment by caugner** [comment]
> Ich würde auch noch Telefonnummern dazu schreiben

Gute Idee, auch wenn ich hier leider kaum Empfang habe.

In #55 schlage ich vor, eine Übersetzung der französischen PM als Zusammenfassung in den Menüpunkt *Presse* zu übernehmen. Wäre das ein Kompromiss?

**Comment by datendelphin** [comment]
> In #55 schlage ich vor, eine Übersetzung der französischen PM als Zusammenfassung in den Menüpunkt Presse zu übernehmen. Wäre das ein Kompromiss?

ja, das finde ich auch gut

**Comment by datendelphin** [comment]
> Wäre das ein Kompromiss?

Meinst du jetzt #55 anstelle von #54 oder den #54 auch mergen?

**Comment by caugner** [comment]
> Meinst du jetzt #55 anstelle von #54 oder den #54 auch mergen?

#54 auf jeden Fall auch mergen (steht aber noch auf Draft, du wolltest sie vermutlich noch kürzen, oder?), aber vielleicht einfach die ausführliche Pressemitteilung beibehalten, aber bevorzugt nur die Zusammenfassung verwenden?

PS: Habe gerade auch noch einmal [beim Presseteam nachgefragt](https://github.com/bleibtoffen/bleibtoffen/issues/37#issuecomment-612647021).

**Comment by datendelphin** [comment]
Ja wollte noch besser diese "Umgekehrte Pyramide" in der Struktur abbilden, aber es kommen mir gerade keine guten Umstellungen mehr in den Sinn.

**Comment by datendelphin** [comment]
Ich schliesse das mal, habe keinen kreativen Ideen mehr

**Comment by caugner** [comment]
> Ich schliesse das mal, habe keinen kreativen Ideen mehr

Dafür kennst du dein Land jetzt in- und auswändig – und kannst einen Vortrag halten über die variable Qualität der Kommunikation der Handelsketten zur aktuellen Situation. :wink:
