### ISSUE TITLE
Buchgeschäfte anzeigen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#56]
Einige Buchgeschäfte bieten Abholung oder Lieferung an.

Da Buchgeschäfte in Deutschland einen hohen Stellenwert haben, sollten wir sie auch anzeigen.

Möglicherweise teilt uns dann auch Sibylle Berg:
![image](https://user-images.githubusercontent.com/495429/79075744-f3a89e80-7cf4-11ea-9cd9-3c7c0279a4dd.png)
([Quelle](https://twitter.com/SibylleBerg/status/1244616197502570497))

**Comment by caugner** [comment]
@chnuessli @datendelphin Sieht das in der Schweiz ähnlich aus?

**Comment by datendelphin** [comment]
Ich kenne nur noch Buchhandelsketten, und die haben alle schon lange einen online Shop, auf welchen nun verwiesen wird.

**Comment by caugner** [comment]
Habe [im overpass turbo](https://overpass-turbo.eu/s/SLl) stichprobenartig mehrere unabhängigen Buchhandlungen gefunden.

**Comment by caugner** [comment]
Upstream: https://github.com/osmontrouge/caresteouvert/issues/321

**Comment by caugner** [comment]
:ok: Buchgeschäfte werden jetzt angezeigt.
