### ISSUE TITLE
Umgang mit Onlineshops die neu "Abholung" anbieten

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#65]
Diverse Online-Shop Anbieter (wie z.B IKEA) bieten aufgrund des erhöhten Bestellaufkommens im Onlineshop und der massiven Überlastung der Post neuerdings Abholungen an.
IKEA ist ein Möbelgeschäft was eigentlich geschlossen ist. Wie mappen wir das? Als partial Opening oder einfach als closed?

**Comment by caugner** [comment]
Interessante Frage, die [englische Wiki-Seite](https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19) wurde gerade vor wenigen Stunden aktualisiert.

Sinngemäß wäre es dann:
1. `opening_hours:covid19=open`
2. `access:covid19=no`
3. `takeaway:covid19=yes`

Wobei wir bei Ketten die Angaben 2 und 3 in der neuen `osm_additional_tags`-Spalte (als JSON!) angeben können, vgl. #64).

**Comment by chnuessli** [comment]
Ich schliesse dieses Issue, die Frage wurde beantwortet. Folgetask wäre wohl im ketten.csv das Tag überall nachzuführen. Da wir dort aber Möbelhäuser wie IKEA gar nicht führen verzichte ich mal darauf.

**Comment by caugner** [comment]
@chnuessli Es spricht nichts dagegen, IKEA in die Liste aufzunehmen.

**Comment by chnuessli** [comment]
Habe Möbelhäuser in die Liste mitaufgenommen
https://github.com/bleibtoffen/bleibtoffen/commit/47d096a52fd63c226da2a61fea671597ffa85f7c
