### ISSUE TITLE
Deutsche Wiki-Seite aktualisieren

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#67]
**Hintergrund**
Die [englische Wiki-Seite zu `opening_hours:covid19`](https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19) wurde am Montag, 13. April, aktualisiert:
https://wiki.openstreetmap.org/w/index.php?title=Key%3Aopening_hours%3Acovid19&type=revision&diff=1979388&oldid=1976725

**Aufgabe**
Die Änderungen sollten in die [deutsche Wiki-Seite](https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours:covid19) übertragen werden.

Bei dieser Gelegenheit sollte auch ein permanenter Link auf die englische Referenzversion eingefügt werden (analog zur englischen Seite, die sich wiederum auf die französische Fassung bezieht).

**Comment by chnuessli** [comment]
Erledigt und Referenzseite verlinkt.
https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours:covid19
