### ISSUE TITLE
Presse-Medien erweitern

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#69]
Vielleicht können wir noch bessere Screenshots u.ä. einstellen?
https://www.bleibtoffen.org/presse.html#medien

**Comment by chnuessli** [comment]
Irgendwo sollte die Botschaft noch klarer herauskommen dass dies keine kommerzielle Webseite ist. Ich vermute vielerlei Medien/Presse denken dass dies ein Angebot ist und wir Geld machen wollen.

**Comment by caugner** [comment]
(Kommentar extrahiert nach #82.)

**Comment by caugner** [comment]
Wir bräuchten jetzt insbesondere noch bessere (und aktuellere) Screenshots.

**Comment by caugner** [comment]
Mangels Ressourcen schließe ich das Issue.
