### ISSUE TITLE
CH: Städte anschreiben

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#71]
# Städte der Schweiz
Die Städte in der Schweiz werden vom offiziellen Twitteraccount des Verein "SOSM" angeschrieben um dem Ganzen etwas Gewicht zu geben. Dies wird durch @datendelphin vorangetrieben.

## Text
Hey @XYZ schon gehört?
Wir haben mit https://bleibtoffen.ch eine Plattform geschaffen, auf der eure Einwohner/innen gezielt, geöffnete Geschäfte finden und Infos über geöffnete Orte mit wenigen Klicks teilen und anpassen können.

In Frankreich wird die Plattform schon von  den grossen Städten und der Regierung genutzt. Hätten Sie Interesse hier mitzumachen?

## To Do

Stadt | Twittername | Twitterlink | Angeschrieben am:
------------ | ------------- | ------------- | -------------
Basel | @BaselStadt | https://twitter.com/BaselStadt (Kanton und Stadt) | 14.04.2020 14:50
Bern | @Bern_Stadt | https://twitter.com/Bern_Stadt | 14.04.2020 19:55
Biel | @BielBienne_off | https://twitter.com/BielBienne_off | 14.04.2020 19:54
Chur | @Churtourismus | https://twitter.com/Churtourismus | 14.04.2020 19:55
Luzern | @stadtluzern | https://twitter.com/stadtluzern | 14.04.2020 19:56
Rapperswil | @stadtrj | https://twitter.com/stadtrj | 14.04.2020 19:56
Schaffhausen | @SH_news | https://twitter.com/SH_news | 14.04.2020 19:57
St.Gallen | @sanktgallen | https://twitter.com/sanktgallen | 14.04.2020 19:57
Thun | @StadtThun | https://twitter.com/StadtThun | 14.04.2020 19:57
Uster | @StadtUster | https://twitter.com/StadtUster | 14.04.2020 19:58
Winterthur | @StadtWinterthur | https://twitter.com/StadtWinterthur | 14.04.2020 19:58
Zug | @gesundZG | https://twitter.com/gesundZG | 14.04.2020 19:58
Zürich | @stadtzuerich | https://twitter.com/stadtzuerich | 14.04.2020 19:59

**Comment by datendelphin** [comment]
Das funktioniert irgendwie nicht. Basel konnte ich anschreiben, Bern, Biel, Chur und Luzern kann man anscheinend nicht direkt anschreiben, und dann bei Rapperswil hiess es dann:

> Feature locked.
> What happened?
> You are sending a Direct Message to users that do not follow you.
> What you can do:
> To unlock this feature, please verify your phone number.

**Comment by caugner** [comment]
> Das funktioniert irgendwie nicht.

Ich habe sie per Tweet angeschrieben.

**Vorteil**: Darauf werden auch andere Leute aufmerksam, warum auch immer.

Jedenfalls gab es gestern bevorzugt Notes aus Städten, die ich angeschrieben habe. Mag aber vielleicht auch einfach nur daran liegen, dass das eben die größten Städten waren und dort die Wahrscheinlichkeit größer ist, dass jemand Daten beiträgt. 😄

**Comment by chnuessli** [comment]
Sali Michael

Ich würde es nicht per DM machen da viele Unternehmensaccounts die DM's blockiert haben.
Man kann diese aber einfach in einem Tweet markieren à la:
Hey @StadtZuerich schon gehört?
Wir haben mit https://bleibtoffen.ch eine Plattform geschaffen, auf der eure Einwohner/innen gezielt, geöffnete Geschäfte finden und Infos über geöffnete Orte mit wenigen Klicks teilen und anpassen können.

Ergibt zwar im Account SOSM sehr viele solcher Tweets, aber sie werden sicher erreicht und zusätzlich hast du noch solche abgedeckt die explizit eine Watch-Funktion auf diese Accounts haben. Claas hat es auch so gemacht, die Einzeltweets danach dann aber irgendwann wieder gelöscht

Gruess Christian

**Comment by caugner** [comment]
> Hey @StadtZuerich schon gehört?

Ich habe mit `@StadtZuerich ...` begonnen, weil ansonsten alle deine Follower diese Tweets in ihre Timeline gespült bekommen. Und dann heißt's: Follower ade!

**Comment by chnuessli** [comment]
> > Hey @StadtZuerich schon gehört?
> 
> Ich habe mit `@StadtZuerich ...` begonnen, weil ansonsten alle deine Follower diese Tweets in ihre Timeline gespült bekommen. Und dann heißt's: Follower ade!

Guter Input, das wusste ich nicht :)

**Comment by chnuessli** [comment]
@caugner Könnten wir das über den bleibtoffen Twitter Account machen? Wäre vermutlich der Sache dienlicher und die SOSM Follower werden nicht mit den Tweets belästigt.

**Comment by caugner** [comment]
@chnuessli Habe dir auf Twitter geschrieben zwecks Zugang.

**Comment by chnuessli** [comment]
So, Städte sind via Twitter angeschrieben, wir sind gespannt.
@chnuessli Idee: Kantone auch anschreiben

**Comment by chnuessli** [comment]
Keinerlei Reaktionen. Kantone haben fast kein Twitter, deswegen verzichten wir wohl darauf. Schliesse dieses Issue somit.
