### ISSUE TITLE
Kontaktformular erstellen

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#76]
Ich würde es noch begrüssen wenn für unerfahrene Nutzer oder Hilfesuchende die mit der Webseite nicht klar kommen, ein Kontaktformular zu Verfügung gestellt wird.

**TBD**
- Wer erhält das Mail?
- Reaktionszeit?
- Spam Schutz?
- pro Land spezifisch?

Diskussion ist eröffnet :)

**Comment by caugner** [comment]
Könnte evtl. an eine eigens eingerichtete Mailingliste gehen?

Mir wäre jede Lösung recht, die nicht Google o.ä. ist, aber mir fällt leider auch gerade keine ein.

**Comment by chnuessli** [comment]
Ich kann nur O365 anbieten, was ja Microsoft wäre und vermutlich in dein o.Ä gehört :)
Kennt ihr sonstige Mailinglisten Anbieter?
