### ISSUE TITLE
Möbelhäuser aufnehmen

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#77]
Möbelhäuser sollen auch auf der Karte angezeigt werden

**Comment by chnuessli** [comment]
Habe ketten.csv, laender.csv und laender.md auf Möbelhäuser angepasst und die Schweizer und ein AT Geschäft hinzugefügt.

**Comment by caugner** [comment]
https://github.com/bleibtoffen/bleibtoffen/commit/47d096a52fd63c226da2a61fea671597ffa85f7c

**Comment by caugner** [comment]
@chnuessli Nur damit ich das richtig verstehe: In der Schweiz dürfen alle Möbelhäuser geöffnet sein?

**Comment by chnuessli** [comment]
Nein, alle müssen Geschlossen bleiben bis Mitte Mai voraussichtlich, damit sie rot markiert sind habe ich sie als Closed in die Liste genommen

Freundliche Grüsse

Christian Nüssli
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Friday, April 17, 2020 6:19:24 PM
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] Möbelhäuser aufnehmen (#77)


@chnuessli<https://github.com/chnuessli> Nur damit ich das richtig verstehe: In der Schweiz dürfen alle Möbelhäuser geöffnet sein?

**Comment by caugner** [comment]
Werden Möbelhäuser derzeit schon angezeigt?

**Comment by chnuessli** [comment]
Leider noch nicht.

Freundliche Grüsse

Christian Nüssli
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Friday, April 17, 2020 6:39:14 PM
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] Möbelhäuser aufnehmen (#77)


Werden Möbelhäuser derzeit schon angezeigt?

**Comment by caugner** [comment]
> Leider noch nicht.

Aber gibt es denn einen Grund, sie vor Mitte Mai anzuzeigen?

**Comment by chnuessli** [comment]
Keinen zwingenden. Aber dann können wir sie auch weglassen, denn dann braucht es die nicht mehr auf der Karte

Freundliche Grüsse

Christian Nüssli
________________________________
Von: Claas Augner <notifications@github.com>
Gesendet: Friday, April 17, 2020 7:36:45 PM
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] Möbelhäuser aufnehmen (#77)


Reopened #77<https://github.com/bleibtoffen/bleibtoffen/issues/77>.

**Comment by chnuessli** [comment]
Wie gehts hier weiter?

**Comment by caugner** [comment]
> Wie gehts hier weiter?

Bisher ist es so, dass in der Karte nur solche Geschäfte angezeigt werden, die grundsätzlich geöffnet sein dürfen.

Möbelhäuser sind jedoch derzeit In Deutschland noch geschlossen und, wie du selbst sagst, in der Schweiz bis Mitte Mai auch noch.

Wäre es erstrebenswert, einfach alle POI-Arten in der Karte als Kategorie/Unterkategorie auswählbar zu machen, jedoch diejenigen *standardmäßig* auszublenden, die derzeit geschlossen sein müssen?

**Comment by chnuessli** [comment]
> Wäre es erstrebenswert, einfach alle POI-Arten in der Karte als Kategorie/Unterkategorie auswählbar zu machen, jedoch diejenigen standardmäßig auszublenden, die derzeit geschlossen sein müssen?

Wäre auch eine Möglichkeit. Was meinst du @datendelphin ?

**Comment by datendelphin** [comment]
Ja, das wäre doch gut. Idealerweise wären die dann alle rot dargestellt wenn aktiviert in der POI Liste, keine Ahnung ob das nun möglich ist.

**Comment by caugner** [comment]
Mit #89 könnten wir sie auch einfach *alle* als geschlossen anzeigen. So viele sind es ja nicht.

Könnte einer von euch die Schweizer Einträge machen? (Erklärung auf den im Issue verlinkten Seiten.)

**Comment by chnuessli** [comment]
Wird erledigt.

**Comment by chnuessli** [comment]
furniture added by @datendelphin. Schliesse diesen Task somit.
