### ISSUE TITLE
App

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#78]
Die Franzosen haben eine App gemacht:
https://twitter.com/caresteouvert/status/1251072902067367936?s=20

Wie sieht es hier mit einem deutschen Ableger aus?

**Comment by chnuessli** [comment]
Zusatz: Die App funktioniert bereits mit unseren Daten (logischerweise). Es fehlt vermutlich nur die Übersetzung.

**Comment by caugner** [comment]
Habe am Freitag nachgefragt, aber keine Antwort erhalten, und nun noch einmal nachgehakt.

PS: Soweit ich verstand, ist die App zunächst nur im französischen App/Play Store. Über F-Droid kann man sie vermutlich überall herunterladen.

**Comment by caugner** [comment]
**Aktueller Stand**: Es wird darüber nachgedacht und um Geduld gebeten.

**Comment by caugner** [comment]
Die App ist inzwischen übersetzt und wird demnächst veröffentlicht.

**Comment by caugner** [comment]
Android-App ist inzwischen auf Deutsch erschienen, die iOS-App noch nicht.
