### ISSUE TITLE
Hotels anzeigen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#88]
@sfkeller und @simonpoole haben in https://github.com/osmontrouge/caresteouvert/issues/315 darum gebeten, Hotels in die Karte aufzunehmen, da einige davon in der Schweiz geöffnet seien:

> AFAIK this is still the situation in Switzerland: "Food stores, takeaway businesses, company canteens, food home delivery services and pharmacies will remain open, as will petrol stations, railway stations, banks, post offices, hotels, public administrations and social institutions. Maintenance facilities for means of transport may remain open."
> 
> Source: https://www.bag.admin.ch/bag/en/home/das-bag/aktuell/medienmitteilungen.msg-id-78454.html (available also in FR and DE).

Quelle: https://github.com/osmontrouge/caresteouvert/issues/315#issuecomment-612619769

> For CH: there are roughly 400 (of around a total of 5000) which are open, with some special cases that are only open for the military. 

Quelle: https://github.com/osmontrouge/caresteouvert/issues/315#issuecomment-616436187

**Comment by caugner** [comment]
@chnuessli Kannst du das bestätigen? Wir sollten dann die `laender.csv` aktualisieren.

**Comment by simonpoole** [comment]
Die Quelle der Information ist der Schweizer Hotelverband mit dem ich in Kontakt bin.

**Comment by chnuessli** [comment]
Hallo @simonpoole und @sfkeller.
Also euer Request wäre Hotels auf der Karte anzuzeigen wissend dass die paar Hotels die geöffnet haben nur Dauergäste oder Militär beherbergen? Ich nehme nicht an dass Hotels neue Gäste aufnehmen.

**Comment by datendelphin** [comment]
Sind die nicht auch für Arbeiter und so geöffnet, um das Pendeln zu vermeiden? Im übrigen waren Hotelbetriebe nicht vom Bund zum schliessen gezwungen worden. Es ist zwar streng davon abgeraten worden, aber es scheint nicht verboten, in der Schweiz in einem Hotel Ferien zu machen.

**Comment by chnuessli** [comment]
Dann müsste man aber streng genommen alle Hotels mal auf "Offen" stellen, ansonsten können den Hotels Nachteile entstehen.
________________________________
Von: datendelphin <notifications@github.com>
Gesendet: Montag, 20. April 2020 19:02
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] Hotels anzeigen (#88)


Sind die nicht auch für Arbeiter und so geöffnet, um das Pendeln zu vermeiden? Im übrigen waren Hotelbetriebe nicht vom Bund zum schliessen gezwungen worden. Es ist zwar streng davon abgeraten worden, aber es scheint nicht verboten, in der Schweiz in einem Hotel Ferien zu machen.

**Comment by simonpoole** [comment]
Wie gesagt nach Liste vom Hotellier Verband sind ca. 400 Hotels (von ~5000 ) offen.

**Comment by caugner** [comment]
Sofern ihr euch einig seid, dass es sinnvoll ist, die Hotels in der Schweiz anzuzeigen, können wir das machen. Es würde dann wohl in die Dienstleistungen-Kategorie fallen (Post, Bank & Co.)

**Comment by caugner** [comment]
Ein Workaround scheint derzeit zu sein, Hotels mit `opening_hours:covid19=open` zu taggen, dann erscheinen sie unter "Sonstige Orte": https://github.com/osmontrouge/caresteouvert/issues/315#issuecomment-616651479

**Comment by caugner** [comment]
Ich habe die Änderung jetzt noch einmal explizit in https://github.com/osmontrouge/caresteouvert/issues/556 angefordert.

**Comment by caugner** [comment]
@simonpoole Hättest du eine Liste der größten Hotelketten mit deren jeweiligen Öffnungsstatus?

**Comment by datendelphin** [comment]
So wie ich das verstanden habe haben wir keine Liste. Der Hotelierverband hat zwar eine, kann die aber nicht rausgeben unter offener Lizenz.

Unsere Hoffnung war jetzt, dass sich die Hotels selber eintragen können. Dass der Verband das an seine Offenen Hotels weiterleitet: da könnt ihr euch eintragen als offen.

 Ich würde jetzt nicht erwarten, dass sich Hotel Ketten einheitlich verhalten. Das wird sehr Standortabhängig sein.

**Comment by caugner** [comment]
Für mich wären "Liste herausgeben" und nennen, welche Hotelketten geöffnet sind, noch zwei unterschiedliche Dinge. Die Antwort auf diese Frage kann auch eigentlich nicht urheberrechtlich geschützt sein (schließlich dürften sich die Antworten auch auf den Webseiten der Ketten finden).

**Comment by simonpoole** [comment]
> Die Antwort auf diese Frage kann auch eigentlich nicht urheberrechtlich geschützt sein ... 

Das ist auch nicht der Grund (ich mach jetzt keinen Abstecher ins Urheberrecht, weil es eh nicht relevant ist), sondern dass sie die Liste aus vertraglichen Gründen nur unter bestimmten Bedingungen herausgeben können und die Bedingungen können wir nicht erfüllen.

**Comment by sfkeller** [comment]
Die einzelnen Hotels entscheiden offensichtlich selber: Ich habe fünf Webseiten der grössten Hotelketten angeschaut und da steht nirgends, dass sie einheitlich schliessen oder einheitlich offen haben. (Nachtrag: Hier habe ich doch noch eine kleine Kette gefunden, die meine vorherige Aussage bestätigt: Sie überlassen es den Hotels und drei von ihnen haben zurzeit noch offen: https://www.biohotels.info/de/urlaubsregionen/schweiz/ ). 

Jeder kann aber (in allen Sprachen - inklusive französisch :-) ) testhalber auf Booking.com nachschauen, dass es z.B. für morgen 2-3 noch offene Hotels hat in Davos. Und hier lese ich https://www.htr.ch/story/hotels-duerfen-wellnessanlagen-und-schwimmbaeder-wieder-oeffnen-27422.html dass die Hotels ab morgen wieder Schwimmbäder öffnen dürfen. Einige planen per Mitte Juni 2020 die Sommersaison zu öffnen.

Wie schon anderweitig gesagt, ist das Hauptproblem auf bleibtoffen, dass Hotels nicht angezeigt werden unabhängig davon, ob sie (noch/wieder) offen sind oder nicht.

P.S. In diesem Sinne sollte übrigens der Teaser-Text von Bleibtoffen (u.a. unter dem Logo links oben) IMHO von "Alle Geschäfte, die weiterhin geöffnet sind" verbessert werden auf "Geschäfte, die weiterhin/wieder offen sind".

**Comment by caugner** [comment]
Ich habe die Info [weitergeben](https://github.com/osmontrouge/caresteouvert/issues/556#issuecomment-619619138) und hoffe, dass die Hotels in den nächsten Tagen ergänzt werden.

**Comment by sfkeller** [comment]
@datendelphin berichtete gestern abend, dass die Hotels nun angezeigt werden.
Tatsächlich sehe ich welche und bei Kategorie "Post, Bank & Co." die Unterkategorie "Unterkunft"!
https://www.bleibtoffen.ch/amenity%2Fhotel@46.804912,9.836277,15.03
Issue kann von mir aus auch geschlossen werden wie https://github.com/osmontrouge/caresteouvert/issues/556#issuecomment-619619138 .
Danke auch an @caugner !
