### ISSUE TITLE
laender.csv nach legal_rules.csv übertragen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#89]
* Beschreibung: https://github.com/PanierAvide/Covid_enseignes#stores-and-services-legally-allowed-to-open-legal_rulescsv
* Ziel: https://github.com/PanierAvide/Covid_enseignes/blob/master/legal_rules.csv

**Comment by datendelphin** [comment]
für CH: https://github.com/PanierAvide/Covid_enseignes/pull/148

**Comment by chnuessli** [comment]
Danke @datendelphin 😊

**Comment by datendelphin** [comment]
Vermutlich gibt es aber noch einige tags, welche noch fehlen, also gerne nochmals draufschauen @chnuessli

**Comment by chnuessli** [comment]
Die Frage ist noch ob wir nun die Hotels so auch mitreinnehmen? Ansonsten scheinen mir die Tags wie auf der laender.csv vollständig zu sein

**Comment by caugner** [comment]
Habe inzwischen auch Deutschland und Österreich übertragen:
https://github.com/PanierAvide/Covid_enseignes/commit/ab9787d6ecf51ce4c832ab4e6e0ce608c36d4113#diff-cf21aaed238073a55d2d7fa7ef60b5b8
