### ISSUE TITLE
Fehler / Änderungen im System kaum rückgängig zu machen

### ISSUE THREAD

**Issue by lud-bmgrt** [bleibtoffen/bleibtoffen#91]
Hallo ihr tüchtiges bleibtoffen-Team,
eine Supersache, was Ihr da macht!
Jetzt habe ich die Schwierigkeit, dass aus irgendeinem Grund eine falsche Öffnungszeit "Sonntag" in bleibtoffen hineingeraten ist. (  https://www.bleibtoffen.de/@47.763695,8.846112,16.65/place/n7158296366   ) Auch unter Zuhilfenahme von JOSM oder anderer Tricks (Sonntag auf 00:00- 00:00 setzen) bekomme ich das in diesem Fall nicht mehr heraus. Warum ist es so schwer, Öffnungszeiten im System zu ändern? Es fehlt dann auch der Button "veröffentlichen".

Gibt es irgendwo eine Mailing-Liste oder eine Stelle im Forum oder FAQs, wo solche Fragen behandelt werden? - denn ich habe noch mehr Frage, auch in Verbindung mit dem Rathaus Singen. Github ist eher etwas für Entwickler, weniger für Nutzer, auch wenn diese aktiv mitmachen.

Ludwig Baumgart  
sh@bwgis.eu   oder  baumgart@bwgis.de

**Comment by ChristineKarch** [comment]
Hallo Ludwig,

man kann alles im JOSM editieren. Allerdings dauert es etwas, bis das auf der Bleibt Offen auch angezeigt wird. Das geht nicht so schnell wie auf der normalen OSM Karte. Eine Stunde oder so, kann das schon dauern.

Ich hab im JOSM den Fahrradladen überprüft, da ist es richtig. Also denke ich, wird es in Kürze auch auf Bleibt Offen richtig erscheinen!

Gruesse

**Comment by caugner** [comment]
Die Änderung ohne Sonntag ist bereits in OSM:
![image](https://user-images.githubusercontent.com/495429/79851393-8b794d00-83c5-11ea-9125-848c67f2f212.png)
(Quelle: https://www.openstreetmap.org/node/7158296366)

Aktuell wird allerdings ein neuer Planet-Datensatz eingespielt, um weitere Orte anzeigen zu können. Daher kommt es derzeit zu Verzögerungen. Bis spätestens heute Abend soll das Update jedoch durchgeführt sein.

PS: Das mit der FAQ-Seite ist eine gute Idee, wozu ich nun #92 erstellt habe.

**Comment by lud-bmgrt** [comment]
hallo liebe Entwickler, auch nach dem Update schaffe ich es nicht, weder mit Josm noch mit bleibtoffen, die falschen Sonntagsöffnungszeiten vom Fahrradhaus Stroppa in Singen aus Eurer bleibtoffen-DB herauszubekommen, zu löschen. In der  osm.org-DB sind diese schon lange nicht mehr. Liegt es evtl. daran, dass es zwei Geschäfte Stroppa an dieser Strasse gibt?
mhG Ludwig

**Comment by chnuessli** [comment]
Hallo @lud-bmgrt Ich habe über bleibtoffen.de die Öffnungszeiten nochmals neu eingetragen. Dann wird die Änderung nochmal neu angestossen. in OSM/JOSM sind alle Öffnungszeiten korrekt.
