### ISSUE TITLE
URL ohne http

### ISSUE THREAD

**Issue by davidbaumann** [bleibtoffen/bleibtoffen#93]
Hallo,
an sich sind die Daten natürlich falsch hinterlegt, aber vielleicht könnte man ja automatisch ein http/https veranstellen, falls eine Homepage ohne eingetragen ist. Aktuell öffnet sich die aktuelle Seite erneut in einem neuen Tab.

**Comment by chnuessli** [comment]
Hallo @davidbaumann 
Da hast du Recht, ansich ist die Datenpflege da meistens falsch. Wir klären mal mit den Franzosen was da möglich ist.
Meistens machen moderne Browser aber aus http sowieso ein https sofern ein Zertifikat vorhanden ist.

**Comment by caugner** [comment]
@davidbaumann Hättest du einen Beispiellink zu „Bleibt offen“ mit einem Ort ohne vorangestelltes http/https in der Website?

**Comment by davidbaumann** [comment]
Node 2736141217.

**Comment by caugner** [comment]
Danke, ich habe dazu ein Issue im frz. Repo erstellt.

**Comment by davidbaumann** [comment]
Super, danke.

**Comment by caugner** [comment]
Der Fall wird nun behandelt. Allerdings führt der Link aus dem Beispiel tatsächlich auf eine offenbar nicht mehr vorhandene Webseite.
