### ISSUE TITLE
Farbe ORANGE für Gaststätten mit Lieferdienst und Rathäuser mit Telefonservice?

### ISSUE THREAD

**Issue by lud-bmgrt** [bleibtoffen/bleibtoffen#94]
Hallo liebes Team,
ein Mitbürger störte sich auch daran, dass die Farbe rot auf dem Gasthaus Lamm in Steisslingen ist, obwohl der Wirt extra einen Abhol/Lieferdienst eingerichtet hat. Natürlich musste er den Normalbetrieb in der Gaststube schliessen. Wäre da nicht die Farbe orange richtiger für diese Form des "eingeschränkt offen"? (wie in der wheelmap "bedingt rollstuhlgerecht"). Ähnliches gilt für ein Hotel, dass nur Stammgäste die von Firmen geschickt werden, aufnimmt. Rot ist sicher richtig für ein anderes Gasthaus/Hotel, das ganz dicht gemacht hat. 
Oder die Rathäuser, die zwar für den Publikumsverkehr geschlossen sind, aber zu den üblichen Zeiten "telefonisch geöffnet" haben. Auch da würde ich mir die Farbe orange wünschen...

Eine andere Anregung: Krankenhäuser mit aufzunehmen?
mhG Ludwig

**Comment by chnuessli** [comment]
Hallo Ludwig

Am besten ändert ihr dann das Wirtshaus auf Grün und setzt die Zusatztags für Take-Away oder Delivery. Entweder kannst du das in die Notiz setzen, dann machen wir das oder direkt in OSM.
Hier die Tags: https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours:covid19

Krankenhäuser sehe ich momentan nicht wirklich, da weiss jeder dass diese offen haben. Wäre dann ein Thema falls wir mal istoffen.de werden :)

Gruss Christian

**Comment by caugner** [comment]
Inzwischen sollten die Antworten "Offen" und "Geschlossen" bei der ersten Frage (statt "Ja" und "Nein") auch etwas klarer machen, dass bei Lieferdienst oder Außer-Haus-Verkauf die Antwort "Offen" gewählt werden sollte:

![image](https://user-images.githubusercontent.com/495429/80314404-c6c6b200-87f1-11ea-8ab8-6187c94b3b08.png)
