### ISSUE TITLE
Input Stammtisch: Flyer erstellen um zu verteilen

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#95]
@ChristineKarch und meine Wenigkeit waren am Stuttgarter Stammtisch.
Diese würden uns mit Flyer unterstützen. Christine hat den Kontakt. FIndet sich jemand diesen Flyer zu entwerfen?

**Comment by CarstenWeithoener** [comment]
Danke noch einmal an Euch beide für die gestrige Präsentation. Ich bin dabei und mache mir gerade erste Gedanken.

**Comment by ChristineKarch** [comment]
Die Geofabrik steht fuer Druck und Versand der Flyer bereit. Mit Versand meine ich, wenn sich jemand meldet bei der Geofabrik und sagt "Bitte x mal den Flyer an mich versenden", schicken wir dort einen dicken Brief hin (genauso wie wir es aktuell mit den OSM Flyern machen).

**Comment by ChristineKarch** [comment]
@caugner haben wir Zugriff auf Design-Elemente von Bleibt Offen? Schriftarten, etc. alles was @CarstenWeithoener dabei helfen könnte, möglichst nah am Web-Design zu bleiben?

**Comment by CarstenWeithoener** [comment]
Die Grafiken der Website sind SVGs. Das ist eine gute Basis. Den Zeichensatz des Logos konnte ich nicht finden.

**Comment by CarstenWeithoener** [comment]
Hier eine leicht bearbeitete Version des Logos. 

[Logov2.zip](https://github.com/bleibtoffen/bleibtoffen/files/4521772/Logov2.zip)

Die Außenmaße sind bewusst gleich geblieben. 

1. Zurichtung der Buchstabenabstände für eine bessere Lesbarkeit.
2. In Deutschland werden Gesundheitsdienste eher mit Rot und Weiß assoziiert. Deshalb die Änderung der Markerfarbe zu Rot. 
3. Dafür hat der Apfel jetzt ein grünes Umfeld. :-)

**Comment by CarstenWeithoener** [comment]
@chnuessli und @caugner Gibt es die Assets der [Presseseite](https://www.bleibtoffen.org/presse.html) und die Grafiken/Banner, die z.B. auf Twitter verwendet werden, auch als svg-Grafiken? Der Logo-Font wäre auch sehr hilfreich.

**Comment by chnuessli** [comment]
@caugner hast du die SVG Files zur Hand?

**Comment by CarstenWeithoener** [comment]
Den Zeichensatz habe ich gefunden. Es ist ein Free-Font: Spirited Sans von [Sam Parrett](https://setsailstudios.com)

**Comment by caugner** [comment]
@CarstenWeithoener Die anderen Assets liegen leider nicht als SVG vor.

**Comment by caugner** [comment]
@CarstenWeithoener Benötigst du noch etwas von mir?

**Comment by CarstenWeithoener** [comment]
@caugner Danke, im Moment komme ich klar.

**Comment by CarstenWeithoener** [comment]
Hier ist der Entwurf für den Flyer. 
Das Format ist das kosten- und versandfreundliche schmale DIN-lang-Format (210 × 100 mm). Als Papier schlage ich ein weißes, kräftiges ungestrichenes Naturpapier vor.  
In erster Linie ist die Gestaltung eine Hommage an die grafischen Arbeiten der französischen Kollegen. Deren Pressemappe war sozusagen mein Steinbruch – hoffentlich gibt es keine Urheberrechtsprobleme. Das Spielerische und Fröhliche der Vorlagen wollte ich unbedingt erhalten; auch wenn in DACH meistens eher sachlicher und minimalistischer gestaltet wird.  Ziel ist es möglichst viele Menschen anzusprechen und Lust auf die Teilnahme zu machen. Gerade auch die zu gewinnen, die keine Informatiker sind und sonst nicht bei OSM mitmachen. Die Voraussetzungen sind wirklich gut, denn die Schwelle für die Teilnehmer ist sehr niedrig. Die Eingabe führt die User selbsterklärend durch die Dateneingabe. Ein großes Kompliment an die Entwickler. 
Der ganze Flyer ist sehr auffordernd gehalten und soll die Einfachheit des Teilnahme in den Vordergrund stellen. Alles Technische und auch sonstige Hintergründe habe ich rausgehalten. Der Text ist bewusst in einfacher Sprache gehalten. 
Über Anregungen zum Text würde ich mich freuen. Nur die Textmenge sollte nicht größer werden. Und an der Beschreibung der drei Schritte würde ich ungern etwas ändern. 
PS: Der Begriff »gemeinnützig« war mir wichtig. Den versteht man zumindest in Deutschland sofort. 

[bleibtoffen_Flyer_DIN_lang_schmal_2S_v2-5_Demo.pdf](https://github.com/bleibtoffen/bleibtoffen/files/4551473/bleibtoffen_Flyer_DIN_lang_schmal_2S_v2-5_Demo.pdf)

**Comment by hbruch** [comment]
Gefällt mir super! 
Da mit dem Farbwechsel für Apfel und Apotheke das blau weggefallen ist, wie würde es wirken, wenn der Haken oder das x-Symbol in blau dargestellt würde, so dass wieder der ursprüngliche 4-Farb-Mix entsteht?

Und wenn ich den Flyer als Gewerbetreibende/r lese, die/der für ihr/sein Geschäft etwas eintragen möchte, wird man durch "werbefrei" und "nicht-kommerziell" eventuell abgeschreckt, weil es ja durchaus um "geschäftliche" Informationen geht, auch wenn so nicht gemeint ist?

**Comment by caugner** [comment]
> Hier ist der Entwurf für den Flyer.

Gefällt mir sehr gut!

> Deren Pressemappe war sozusagen mein Steinbruch – hoffentlich gibt es keine Urheberrechtsprobleme.

Theoretisch könnte es diese Probleme geben. Florian von CRO hat mir gegenüber zwar in einem Skype-Gespräch die Nutzung der Grafiken eingeräumt, aber es wäre besser, wenn dies noch in irgendeiner Form verschriftlicht würde, z.B. im CRO-Impressum.

> PS: Der Begriff »gemeinnützig« war mir wichtig. Den versteht man zumindest in Deutschland sofort.

Auf der Webseite hatte ich "gemeinnützig" bewusst nicht aufgezählt, weil ich juristische Schwierigkeiten befürchtet habe. Dürfen wir das Projekt gemeinnützig nennen, auch wenn diese Gemeinnützigkeit nicht von den zuständigen Behörden anerkannt wurde?

> `Wieviele Kunden dürfen die Apotheke gleichzeitig betreten?`

`Wie viele` müsste in zwei Worten geschrieben werden. Allerdings: Theoretisch lässt sich das mit `capacity:covid19` erfassen, aber es gibt derzeit keine Erfassungsmaske dafür. Neuerdings gibt es die Möglichkeit anzugeben, ob Desinfektionsmittel und Masken vorrätig sind (diese Daten werden *nicht* in OSM gespeichert). Das könnte man stattdessen erwähnen.

> `Hat Dein Gemüsehändler`
> `geöffnet?`

Bis vor kurzem habe ich "du", "dein" usw. auch noch überwiegend großgeschrieben, auf dem Flyer würde ich aber eher die Kleinschreibung verwenden, weil üblicher und besser lesbar.

**Comment by CarstenWeithoener** [comment]
>Da mit dem Farbwechsel für Apfel und Apotheke das blau weggefallen ist, wie würde es wirken, wenn der Haken oder das x-Symbol in blau dargestellt würde, so dass wieder der ursprüngliche 4-Farb-Mix entsteht?

Das funktioniert nicht so gut, weil der Schatten der Marker blau ist. Die brauchten den Schatten, um sich vom Hintergrund abzuheben. Ich denk aber noch einmal nach. 

>Und wenn ich den Flyer als Gewerbetreibende/r lese, die/der für ihr/sein Geschäft etwas eintragen möchte, wird man durch "werbefrei" und "nicht-kommerziell" eventuell abgeschreckt, weil es ja durchaus um "geschäftliche" Informationen geht, auch wenn so nicht gemeint ist?

Da hast Du vermutlich recht. Ich mache mir Gedanken. Zumal @caugner mit seiner Vermutung zur Gemeinnützigkeit richtig liegt.

**Comment by CarstenWeithoener** [comment]
> Theoretisch könnte es diese Probleme geben. 

Es wäre schade, wenn das Projekt an den Ländergrenzen optisch zerfallen würde. Auf der Rückseite der [Pressemappe](https://blog.caresteouvert.fr/wp-content/uploads/2020/04/Dossier-de-presse-%C3%87a-reste-ouvert.pdf) befindet sich übrigens ein Creative-Commons-Logo. 

>Auf der Webseite hatte ich "gemeinnützig" bewusst nicht aufgezählt, weil ich juristische Schwierigkeiten befürchtet habe. 

Du liegst offensichtlich richtig. Ich hatte im Netz nachgesehen und war davon ausgegangen, dass der Begriff nicht geschützt ist. Nicht nur [Wikipedia](https://de.wikipedia.org/wiki/Gemeinnützigkeit) ist anderer Meinung. 

>Theoretisch lässt sich das mit capacity:covid19 erfassen, (…) Das könnte man stattdessen erwähnen.

Ich hab’s anders gelöst: »Hat dein Gemüsehändler geöffnet? Bietet die Apotheke einen Lieferservice oder dein Lieblingsrestaurant einen Abholservice?«

>Du Dein Dich etc. 

Das war meinem fortgeschrittenen Alter geschuldet. ;-)

**Comment by caugner** [comment]
> Auf der Rückseite der Pressemappe befindet sich übrigens ein Creative-Commons-Logo.

Stimmt, hatte ich ganz vergessen, dass die Pressemappe ist unter CC. Allerdings sind die (französische) Marke und das Logo urheberrechtlich geschützt.

Eine Kleinigkeit noch:

> `weltweit`

Ist nicht ganz richtig, die Karte funktioniert nur in freigeschalteten Gebieten gemäß folgender Zeile:

https://github.com/osmontrouge/caresteouvert/blob/master/categories.json#L2

**Comment by ChristineKarch** [comment]
Dürfen wir vor dem Drucken noch ein kleines Rechteck mit einer Geofabrik-Werbung einfügen. Äquivalent wie wir es beim OSM-Flyer auf dieser Seite machen:

[osmflyer1.pdf](https://github.com/bleibtoffen/bleibtoffen/files/4554623/osmflyer1.pdf)

Der Vollständigkeit halber hier noch die zugehörige zweite Seite:

[osmflyer2.pdf](https://github.com/bleibtoffen/bleibtoffen/files/4554627/osmflyer2.pdf)

Dieser Flyer wird zu DIN A7 gefaltet. Wenn ich es richtig sehe, wird unser Bleibt Offen Flyer einfach einmal in der Mitte gefaltet oder?

Die Geofabrik würde die Flyer bestellen, bezahlen und bei sich lagern. Die Interessierten können sie ohne Kosten bei "info@geofabrik.de" bestellen.

**Comment by chnuessli** [comment]
Sehr cooler Flyer.
@Christine Karch<mailto:christine@hermione.de> keine Einwände gegen euer Logo.
________________________________
Von: Christine Karch <notifications@github.com>
Gesendet: Mittwoch, 29. April 2020 23:17
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] Input Stammtisch: Flyer erstellen um zu verteilen (#95)


Dürfen wir vor dem Drucken noch ein kleines Rechteck mit einer Geofabrik-Werbung einfügen. Äquivalent wie wir es beim OSM-Flyer auf dieser Seite machen:

osmflyer1.pdf<https://github.com/bleibtoffen/bleibtoffen/files/4554623/osmflyer1.pdf>

Der Vollständigkeit halber hier noch die zugehörige zweite Seite:

osmflyer2.pdf<https://github.com/bleibtoffen/bleibtoffen/files/4554627/osmflyer2.pdf>

Dieser Flyer wird zu DIN A7 gefaltet. Wenn ich es richtig sehe, wird unser Bleibt Offen Flyer einfach einmal in der Mitte gefaltet oder?

Die Geofabrik würde die Flyer bestellen, bezahlen und bei sich lagern. Die Interessierten können sie ohne Kosten bei "info@geofabrik.de<mailto:info@geofabrik.de>" bestellen.

**Comment by CarstenWeithoener** [comment]
Hier der überarbeitete Flyer; ich habe möglichst viele eurer sehr konstruktiven Anregungen aufgenommen. 

Es gibt eine deutsche und eine schweizerische Version. 
Sie unterscheiden sich folgendermaßen: 

1. TLD: de <-> ch
3. Die Markerfarben auf der Vorderseite
2. Pressekontakt: Claas Augner <-> Stefan Keller

Das Logo "Ça reste ouvert" ist ein eingetragenes Markenzeichen, auch deshalb habe ich einen Copyright-Hinweis von "junglebus" dazwischen gequetscht. 

Freue mich weiterhin über Feedback. Bin aber auch froh, wenn er bald gedruckt wird. 

Wenn hier Konsens besteht, werde ich die fertigen Druckdaten an @ChristineKarch weiterleiten und hier einstellen
[Flyer_DIN_lang_schmal_100x210mm_2Seiten_CH_Demo.pdf](https://github.com/bleibtoffen/bleibtoffen/files/4570855/Flyer_DIN_lang_schmal_100x210mm_2Seiten_CH_Demo.pdf)
[Flyer_DIN_lang_schmal_100x210mm_2Seiten_DE_Demo.pdf](https://github.com/bleibtoffen/bleibtoffen/files/4570856/Flyer_DIN_lang_schmal_100x210mm_2Seiten_DE_Demo.pdf)

. 

Gerne stelle ich auch die, leider proprietäre, Indesign-Datei hier ein. Der Flyer, zumindest mein Beitrag, steht unter CC0-Lizenz.

**Comment by caugner** [comment]
Ist super geworden, von meiner Seite aus keine Einwände gegen den Druck. :-)

**Comment by chnuessli** [comment]
Hallo Carsten

Herzlichen Dank für deine Arbeit.
Sieht wirklich super aus, danke auch an die GeoFabrik @Christine Karch<mailto:christine@hermione.de>
________________________________
Von: CarstenWeithoener <notifications@github.com>
Gesendet: Sonntag, 3. Mai 2020 17:24
An: bleibtoffen/bleibtoffen <bleibtoffen@noreply.github.com>
Cc: Christian Nüssli <chrigi@chnuessli.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [bleibtoffen/bleibtoffen] Input Stammtisch: Flyer erstellen um zu verteilen (#95)


Hier der überarbeitete Flyer; ich habe möglichst viele eurer sehr konstruktiven Anregungen aufgenommen.

Es gibt eine deutsche und eine schweizerische Version.
Sie unterscheiden sich folgendermaßen:

  1.  TLD: de <-> ch
  2.  Die Markerfarben auf der Vorderseite
  3.  Pressekontakt: Claas Augner <-> Stefan Keller

Das Logo "Ça reste ouvert" ist ein eingetragenes Markenzeichen, auch deshalb habe ich einen Copyright-Hinweis von "junglebus" dazwischen gequetscht.

Freue mich weiterhin über Feedback. Bin aber auch froh, wenn er bald gedruckt wird.

Wenn hier Konsens besteht, werde ich die fertigen Druckdaten an @ChristineKarch<https://github.com/ChristineKarch> weiterleiten und hier einstellen
Flyer_DIN_lang_schmal_100x210mm_2Seiten_CH_Demo.pdf<https://github.com/bleibtoffen/bleibtoffen/files/4570855/Flyer_DIN_lang_schmal_100x210mm_2Seiten_CH_Demo.pdf>
Flyer_DIN_lang_schmal_100x210mm_2Seiten_DE_Demo.pdf<https://github.com/bleibtoffen/bleibtoffen/files/4570856/Flyer_DIN_lang_schmal_100x210mm_2Seiten_DE_Demo.pdf>

.

Gerne stelle ich auch die, leider proprietäre, Indesign-Datei hier ein. Der Flyer, zumindest mein Beitrag, steht unter CC-Lizenz.

**Comment by CarstenWeithoener** [comment]
Sehr gerne, ich freue mich, dass er euch gefällt. 

Für Änderungen, Weiterentwicklungen des Flyers oder weitere grafische Arbeiten könnt ihr euch jederzeit und gerne bei mir melden. 

@ChristineKarch 

Hier sind die Druckvorlagen: 

Für Deutschland: [Flyer_DIN_lang_schmal_100x210mm_2Seiten_DE_Druck_PF.pdf](https://github.com/bleibtoffen/bleibtoffen/files/4580031/Flyer_DIN_lang_schmal_100x210mm_2Seiten_DE_Druck_PF.pdf)

Für die Schweiz: [Flyer_DIN_lang_schmal_100x210mm_2Seiten_CH_Druck_PF.pdf](https://github.com/bleibtoffen/bleibtoffen/files/4580034/Flyer_DIN_lang_schmal_100x210mm_2Seiten_CH_Druck_PF.pdf)

**Das Technische, die Angaben für die Druckerei:** 

- Die PDF-Dateien sind PDF/X-1a-kompatibel 
- Das Endformat ist DIN lang schmal quer: 210 × 100 mm
- Die Beschnittzugabe beträgt umlaufend 2 mm: 214 × 104 mm 
- Das Papier: hochweißes, ungestrichenes Offsetpapier, mind. 250 g/qm

@caugner Es gibt Werte für shop=*  die nicht angezeigt werden, z. Bsp. health_food. Wo kann ich das melden/eintragen? Auch shop-Werte mit Semikolon werden ignoriert, Beispiel "shop=optician;hearing_aids".

Vaihingen an der Enz wird übrigens immer [grüner](https://www.bleibtoffen.de/@48.931718,8.957361,16.42). :-)

**Comment by ChristineKarch** [comment]
Der Druckauftrag ist raus, wir bekommen die Flyer (DE und CH) am 11.5. Aber wir können die Werbung dafür gerne schon jetzt machen. Ich kann das auf der deutschen Mailingliste übernehmen. Die Schweizer Werbung müsste jemand anderes übernehmen. @chnuessli :)

**Comment by ChristineKarch** [comment]
Nach Rücksprache mit den Schweizern haben wir den schweizer Flyer gecancelt. Den deutschen haben wir aber bestellt. Ab 11. Mai kann der Versand beginnen. Bestellt kann jetzt schon werden unter info@geofabrik.de

**Comment by datendelphin** [comment]
Noch als etwas Kontext wegen der Schweizer Version: Ab 11. Mai dürfen alle Läden und auch Restaurants wieder öffnen, darum wäre es etwas schlechtes Timing, ab nächster Woche diese flyer zu verteilen.
Trotzdem vielen herzlichen Dank an alle, schöner Flyer.

**Comment by chnuessli** [comment]
Flyer für Deutschland stehen zu Verfügung und können über GeoFabrik bestellt werden. Ich schliesse diesen Input Task.

Danke allen Beteiligten für das riesige Engagement.
