### ISSUE TITLE
Pubs anzeigen

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#96]
Pubs werden auf der Karte nicht dargestellt.

**Comment by caugner** [comment]
Es werden derzeit nur Kneipen angezeigt, die grundsätzlich Lieferung bzw. Außer-Haus-Verkauf anbieten:

https://github.com/osmontrouge/caresteouvert/blob/0cce79c21676581e2a4cd0930942b9acf6bfd5fa/categories.json#L335-L349

**Comment by chnuessli** [comment]
@sfkeller Deswegen wird das Nelson Pub nicht angezeigt.

**Comment by sfkeller** [comment]
Alles klar.

P.S. Aber bei Hotels gibt's keinen anderen Weg als sie anzuzeigen: https://github.com/osmontrouge/caresteouvert/issues/315#issuecomment-619367311 .
