### ISSUE TITLE
Wiki-Artikel verschlechtert

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#97]
Unser übersetzter Wiki Artikel wurde von einem User bearbeitet.
Leider hat er die ganzen Tag Beschreibungen rausgelöscht. Sollen wir hier intervenieren?

Change: https://wiki.openstreetmap.org/w/index.php?title=DE:Key:opening_hours:covid19&diff=next&oldid=1982697

**Comment by datendelphin** [comment]
Ich würde die Französische Seite als Ursprung der Übersetzung ansehen. Und die haben eben auch diese Umsortierung gemacht: https://wiki.openstreetmap.org/wiki/FR:Covid-19_-_how_to_map sind nun die zusammengefassten Informationen über alle Tags, während die https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours:covid19 Tag Seite nur noch Infos zum eigentlichen tag enthält

Ich würde vorschlagen, die https://wiki.openstreetmap.org/wiki/DE:Covid-19_-_how_to_map zu vervollständigen und die Links umzusetzen. Und natürlich diese Seite aus der deutschen Übersetzung für den Tag verlinken

**Comment by caugner** [comment]
Ich stimme @datendelphin zu, dass alle Infos in die neue Covid-19-Seite übertragen werden sollte (in richtigem Deutsch).

Anschließend werde ich den Link in den OSM-Notizen anpassen: https://github.com/osmontrouge/caresteouvert_backend/blob/7ca5686bec917af700b374aaa8f7e1c222d8de46/locales/de.json#L12

**Comment by chnuessli** [comment]
Wurde umgesetzt
