### ISSUE TITLE
CH: Geschäfte wieder offen

### ISSUE THREAD

**Issue by chnuessli** [bleibtoffen/bleibtoffen#98]
Inwiefern müssen wir ab 11. Mai die ketten.csv und laender.csv anpassen weil dann bis auf Grossveranstaltungen alles wieder offen hat? 
Quelle: https://www.bag.admin.ch/bag/de/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov.html

@caugner Kann man alle Geschäfte "bulk"-mässig öffnen?

**Comment by caugner** [comment]
Gute Frage, ich habe bei CRO nachgefragt: https://github.com/osmontrouge/caresteouvert/issues/621

**Comment by datendelphin** [comment]
Ab jetzt sind fast alle Geschäfte wieder geöffnet. Auf der Karte werden aber immer noch gewisse grau und rot dargestellt. Ich sehe das auch wie caugner: Wäre super, die shop Karte und den opening hours editor weiter nutzen zu können, aber solange da noch alles sich nach den covid tags richten, macht es vor allem einen outdated Eindruck.
Vielleicht sollte ich eher das osmontrouge/caresteouvert#621 kommentieren. Das scheint etwas ins Stocken geraten zu sein.
Ich bin mir bewusst das ist mega viel Arbeit, vielleicht haben wir uns da etwas zu viel vorgenommen. Aber für eine langfristige Wirkung für OSM ist dieser übergang ein ein essentieller Punkt schätze ich.

**Comment by caugner** [comment]
Laut [legal_rules.csv](https://github.com/PanierAvide/Covid_enseignes/blob/master/legal_rules.csv) sind die Geschäfte in der Schweiz bis einschließlich heute standardmäßig geschlossen. Das Datum müsste wohl auf gestern geändert und eine neue `default`-Regel ab heute hinzugefügt werden.

**Comment by datendelphin** [comment]
Ups das ist mein Fehler. Typisch, off by one.
