### ISSUE TITLE
Geschäfte fehlen

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen#99]
@CarstenWeithoener schrieb in https://github.com/bleibtoffen/bleibtoffen/issues/95#issuecomment-623967759:

> Es gibt Werte für shop=* die nicht angezeigt werden, z. Bsp. health_food. Wo kann ich das melden/eintragen? Auch shop-Werte mit Semikolon werden ignoriert, Beispiel "shop=optician;hearing_aids".

**Comment by caugner** [comment]
@CarstenWeithoener In diesem Upstream-Issue siehst du den aktuellen Stand: https://github.com/osmontrouge/caresteouvert/issues/558#issuecomment-619889781

Knackpunkt sind derzeit fehlende Icons für diese Geschäfte. Geschäfte mit weniger als 1000 POIs fehlen zudem bisher komplett.

Hättest du ein konkretes Beispiel für `shop=optician;hearing_aids`? Wie werden diese denn auf OpenStreetMap.org angezeigt?

**Comment by CarstenWeithoener** [comment]
>Hättest du ein konkretes Beispiel für shop=optician;hearing_aids? Wie werden diese denn auf OpenStreetMap.org angezeigt?

https://www.openstreetmap.org/node/4895786026

https://www.bleibtoffen.de/@48.928243,8.962382,19.41

Mapnik behilft sich mit einem lila Punkt. Übrigens auch bei health_food (Bioläden und Reformhäuser)

https://www.openstreetmap.org/node/324242056

**Comment by caugner** [comment]
OpenStreetMap.org kann den Punkt offenbar auch keiner Kategorie zuordnen:

![grafik](https://user-images.githubusercontent.com/495429/81063934-0586f700-8ed9-11ea-8a63-122a3d111f12.png)

Wäre es nicht sinvoller, den Shop als `shop=medical_supply` zu taggen oder in zwei Nodes aufzusplitten?

Solche Spezialfälle ([29 Objekte laut Taginfo](https://taginfo.openstreetmap.org/tags/shop=optician;hearing_aids)) sind out of scope für Bleibt offen, es sei denn wir zeigen `shop=*`  (außer `shop=yes|vacant`) an.

Aus technischen Gründen unterstützt BO bisher auch nur eine Kategorie pro POI.

**Comment by CarstenWeithoener** [comment]
>Wäre es nicht sinvoller, den Shop als shop=medical_supply zu taggen oder in zwei Nodes aufzusplitten?

@caugner Eher nicht. Es handelt sich m.M. nach um ein ungelöstes OSM-Tagging-Thema. Ein ähnliches Problem gibt es bei Bäckerei + Café, Restaurant + Biergarten, Café + `outdoor_seating=*`. Eigentlich gehört es zusammen hat aber oft unterschiedliche Eigenschaften (`opening_hours=*`, `smoking=*` etc.). 

>Aus technischen Gründen unterstützt BO bisher auch nur eine Kategorie pro POI.

>Solche Spezialfälle (29 Objekte laut Taginfo) sind out of scope für Bleibt offen, es sei denn wir zeigen shop=* (außer shop=yes|vacant) an.

So wenige. Dann mache ich doch zwei POIs daraus.

**Comment by CarstenWeithoener** [comment]
@caugner Wie kann man Icons beisteuern. Welche Größe(n) sollen sie haben und in welchem Dateiformat? Gibt es evtl. Templates?

**Comment by caugner** [comment]
Alle bisherigen Icons liegen als einfarbige (schwarz) SVG-Datei in 18x18 in diesem Verzeichnis: https://github.com/osmontrouge/caresteouvert/tree/master/icons

Der Name des Icons ergibt sich aus dem Namen der Kategorie, der meist mit dem Wert des `shop`-Keys übereinstimmt, z.B. `hardware`, siehe Kategorie-Liste:

https://github.com/osmontrouge/caresteouvert/blob/10e143e876b03919471d8745a6afd040f68c3d5b/categories.json#L423

Fehlende Kategorien müssten auch in der `categories.json` ergänzt werden, aber das könnte ich im Zweifel auch übernehmen.

Es gibt leider [sehr, sehr viele shop-Werte](https://github.com/osmontrouge/caresteouvert/issues/558#issuecomment-619834177).

**Comment by CarstenWeithoener** [comment]
@caugner Hier sind ein paar Icons. Einige habe ich gezeichnet, andere Vorlagen habe ich von Wikimedia Commons und meist verändert; die Quellen kann ich auf Wunsch dokumentieren. 

Ich frage mich, warum ein Icon nicht mehrere Shops repräsentieren kann. 

Das Hemd für: boutique|clothes|fashion|fashion_accessories

Werkzeug für: hardware|doityourself

Die Wimpern: beauty|cosmetics|perfumery
 
Das Auto für: car_repair|car|car_parts|tyres|car_rental …

**Die Icons**

[amenity_SVGs.zip](https://github.com/bleibtoffen/bleibtoffen/files/4596278/amenity_SVGs.zip)

toilets, bank

[shop_SVGs.zip](https://github.com/bleibtoffen/bleibtoffen/files/4596279/shop_SVGs.zip)

weapons, art, charity, coffee, fishing, frame, health_food, interior_decoration, laundry, locksmith, photo, pottery, seafood, tailor, travel_agency, watch

**Comment by CarstenWeithoener** [comment]
@caugner Noch ein paar Shop-Icons, und ein zwei Icons von gestern in verbesserter Version. 

[shop_SVGs-2.zip](https://github.com/bleibtoffen/bleibtoffen/files/4599868/shop_SVGs-2.zip)

interior_decoration-2, medical_supply, dry_cleaning, laundry-2, department_store, tickets, houseware, music

**car-Icon**

![verrutschtes_Auto_Icon](https://user-images.githubusercontent.com/63249420/81421322-9b2cbb80-9151-11ea-9050-86ba11fa709c.png)


Das Icon ist etwas nach oben gerutscht.

**Comment by caugner** [comment]
Ich habe nun einige deiner Icons in https://github.com/osmontrouge/caresteouvert/pull/722 ergänzt (Merge ausstehend).

@CarstenWeithoener Eine Checkliste der Shops mit mehr als 1000 Geschäften in Deutschland findest du hier:
https://github.com/osmontrouge/caresteouvert/issues/558#issuecomment-619889781

**Comment by caugner** [comment]
Was also insbesondere noch fehlt:

- [ ] mall
- [ ] tattoo
- [ ] craft
- [ ] antiques
- [ ] bookmaker (?)
- [ ] locksmith
- [ ] lottery (?)
- [ ] erotic
- [ ] baby_goods
- [ ] leather
- [ ] frame
- [ ] photo_studio
- [ ] solarium
- [ ] estate_agent
- [ ] radiotechnics
- [ ] rental
- [ ] pawnbroker
- [ ] scuba_diving (?)
- [ ] pet_grooming
- [ ] window_blind
- [ ] storage_rental

**Update**: Ich habe die Liste aktualisiert (vgl. [Original](https://github.com/osmontrouge/caresteouvert/issues/558#issuecomment-619889781)). Alle Kategorien, die ich in https://github.com/osmontrouge/caresteouvert/pull/722 ergänze, sind hier bereits als "erledigt" markiert.

**Comment by CarstenWeithoener** [comment]
frame.svg und locksmith.svg sind bereits im zip-Archiv shop_SVGs.zip enthalten. 

In [shop_SVGs-3.zip](https://github.com/bleibtoffen/bleibtoffen/files/4606957/shop_SVGs-3.zip) sind: mall, second_hand und lottery enthalten. Letzteres (vierblättriges Kleeblatt) würde ich auch für den bookmaker verwenden. 

Für Fotostudios schlage ich photo.svg vor.

**Comment by CarstenWeithoener** [comment]
@caugner Ich bin ja lernfähig. :-) Nachdem ich gesehen habe, dass meine Icons in der Abbildungsgröße, überhaupt nicht funktionieren, habe ich nachgebessert. Die Icons sind jetzt viel grober und deshalb besser zu erkennen. 

[shop_SVGs-4.zip](https://github.com/bleibtoffen/bleibtoffen/files/4610746/shop_SVGs-4.zip)

- mall
- department_store
- health_food
- art
